### ISSUE TITLE
[SUGGESTION] Allow users to use the accountview features without requiring to be logged in

### ISSUE THREAD

**Issue by SammyGuichelaar** [AppTapp/Installer-Issues#1]
**Is your feature request related to a problem? Please describe.**
Some features of Installer [eg purchased packages] are currently only accessible if a user has logged into their AppTapp account, while there is no reason for this requirement. 

**Describe the solution you'd like**
We should show the current 'AccountView' without requiring a login, and instead offer the user an option to login if he or she wishes to do so.

**Comment by CreatureSurvive** [comment]
Added in RC10.2
