### ISSUE TITLE
[CRASH] - Auto refresh when opening installer

### ISSUE THREAD

**Issue by DrFA** [AppTapp/Installer-Issues#10]
**Describe the crash**
Simply launch the installer, when it attempts to auto refresh it crashes

**To Reproduce**
As above
**Expected behavior**
a smooth fast auto refresh without the crash
**Screenshots**

**Device (please complete the following information):**
 - Device: iphone X
 - OS: ios 13.3
 - Installer version Rc6
 - Jailbreak checkra1n 0.97

**Additional context**

**Crashlog -- REQUIRED** 

https://pastebin.com/mn0e58n9

**Comment by AppTapp** [comment]
@Oxycodon-IV Please attach a crashlog, without it we cannot debug the issue properly.

**Comment by CreatureSurvive** [comment]
I believe this issue has been fixed, if you still experience this crash after the next release, then please leave another comment here so that I can continue working on this.

**Comment by DrFA** [comment]
Great, waiting for the next release and will let you know

**Comment by DrFA** [comment]
Issue fixed- but there is a heavy delay with the auto refresh completing when opening installer but no more crashing

**Comment by CreatureSurvive** [comment]
Thanks for getting back to us about this, I will go ahead and close this issue and open a new one for the lag during auto refresh. Hopefully that won’t be too difficult to resolve.

**Comment by DrFA** [comment]
https://psty.io/p?q=c35c8

**Comment by DrFA** [comment]
Here is another:

https://psty.io/p?q=3154c

**Comment by CreatureSurvive** [comment]
This one has been difficult to trace, the crash logs have not been much help in debugging. I’m in the process of rewriting multiple view controllers to be more performant and use less resources. I’m hoping that during these rewrites, that the underlying cause of this issue will be resolved. I’ll try and keep this issue thread updated with any progress I make in resolving the lag/crashes.

**Comment by CreatureSurvive** [comment]
Fixed in RC10
