### ISSUE TITLE
[BUG] Blank Space on the Bottom of the Changes Tab

### ISSUE THREAD

**Issue by mpelteshki** [AppTapp/Installer-Issues#103]
**Describe the bug**
After scrolling down to the bottom of the Changes tab, there’s a big gap between the last package and the ‘See older Packages’ text. 

**Does the issue always occur when trying to reproduce it?** 
Yes

**Expected behavior**
I expect the ‘see older packages’ text to appear just below the last package.

**Screenshots or videos**
![1E95D5E2-CD1E-4A56-BBC7-0E6B4D8BB482](https://user-images.githubusercontent.com/39273158/103422205-e8f6a800-4ba8-11eb-86ab-f7da0dc41e72.png)

**Device (please complete the following information):**
 - Installer version: [5.1-70]
 - iOS: [iOS 14.2]
 - Jailbreak [Odysseyra1n]
 - Device [iPhone 7]

**Comment by AppTapp** [comment]
Thank you for your report, we’ll fix this asap.

**Comment by SynnyGR** [comment]
This issue have been fixed. The fix should be available within the next beta ;)
