### ISSUE TITLE
[BUG] Logging into AppTapp account fails (Impossible to connect)

### ISSUE THREAD

**Issue by audris42** [AppTapp/Installer-Issues#106]
![A75E2392-6B6F-447C-A49B-1C780012CD06](https://user-images.githubusercontent.com/5376166/103423920-ea74a000-4ba9-11eb-9da4-168f3cb62bff.png)
**Describe the bug**

impossible to connect, at each change of word exceeded, impossible to connect.

**To Reproduce**
Steps to reproduce the behaviour:

**Does the issue always occur when trying to reproduce it?** 
Yes

**Expected behavior**

**Screenshots or videos**
If applicable, add screenshots or videos to help explain your problem.

**Device (please complete the following information):**
 - Installer version: 5.1
 - iOS: iOS 14.0.1
 - Jailbreak : Checkra1n
 - Device :iPhone 7 (9,3)

**Comment by AppTapp** [comment]
Can you confirm this happens on Mobile Data connection too? We cannot replicate this issue.

**Comment by audris42** [comment]
Yes
![8E451BEB-3A63-4399-97E1-736465B87E6B](https://user-images.githubusercontent.com/5376166/103424278-8c48bc80-4bab-11eb-9061-d76579ea6eeb.png)

**Comment by audris42** [comment]
.

**Comment by audris42** [comment]
https://mega.nz/file/jVpSwKjY#0QjBHuTH3f3JjRXAsIKFPPYIE9Nj7ZmuxPirpSEDlpo

**Comment by oldman20** [comment]
Same issue, alway can’t login. But when open setting apptapp, it’s showing logined, but im sure it’s not true

**Comment by SynnyGR** [comment]
Hi there,

This issue have just been fixed, the fix should be available within the next beta ;)
It's an issue affecting people who have another language than English set but like @oldman20 said, the login is still effectively done so just click on OK.

Have a nice day.

Regards
