### ISSUE TITLE
[SUGGESTION] Automatic Switching between Light and Dark Mode According to System Settings

### ISSUE THREAD

**Issue by mpelteshki** [AppTapp/Installer-Issues#107]
**Is your feature request related to a problem? Please describe.**
I usually use all my apps in light mode during the day and in dark mode in the night. Its frustrating to have apps that don’t comply with my system settings.

**Describe the solution you'd like**
I’d like installer to have an option to automatically switch between light and dark mode according to the system

**Comment by SynnyGR** [comment]
Assigned to Dave according to him starting the dev of this feature

**Comment by vanwijkdave** [comment]
Feature is at 70%: working in theory, but needs a relaunch of the app. I'll try to make it be able to switch on the fly

**Comment by Janneske2001** [comment]
I don't know if I should post it here, but for me (iPhone 8, iOS 14.2 and 14.3, Odysseyra1n and Checkra1n) it works on the fly. Feels pretty native to me. Well done. 👍 (latest update, so I think it's solved)

**Comment by SynnyGR** [comment]
Auto switch is now enabled and doesn't need relaunching the app anymore for the change to take effect.
This nex feature should be available in the next update.

Have a nice day!

Regards
