### ISSUE TITLE
Inconsistent Design Language in Modify/Get buttons

### ISSUE THREAD

**Issue by mpelteshki** [AppTapp/Installer-Issues#109]
**Describe the issue**
Some Modify/Get buttons(e.g. in the installed, changes and home tabs) have this translucent design with bolder text in the middle, which I really like. 
![145BEBD1-3D30-401D-B4F7-4745FD7FD0D5](https://user-images.githubusercontent.com/39273158/103424807-29f5b900-4bb7-11eb-9f51-ceda2797f51e.png)
After entering a package depiction though, the transparency part of the buttons is gone
![45890FF8-7684-4011-A86D-31BD3AB01026](https://user-images.githubusercontent.com/39273158/103424863-6d502780-4bb7-11eb-8fae-55e99313c6d6.png)

**Does the issue always occur when trying to reproduce it?**
Yes

**Expected behavior**
I think it would look better if the same design language for the buttons from the home, changes and installed tabs was carried over to the depiction pages of tweaks.
For example:
![FB3C5C25-C1C9-45DD-94DD-B554C5FD7F28](https://user-images.githubusercontent.com/39273158/103424937-dcc61700-4bb7-11eb-84ba-eeace1156e04.png)
I think the get buttons would look great if they looked like the ‘more’ button from the screenshot.

**Comment by AppTapp** [comment]
The ‘Get’ buttons in the depictions are adaptive to the colour which is specified in the depiction, so we can’t really change that without disabling the adaptive buttons which is one of the things which makes the depictions look nice for most packages. 

For example, this is what the buttons look like in the ‘QuitAll’ depiction. 
![2819B6B8-7DD3-4852-9FF3-11E43072A329](https://user-images.githubusercontent.com/35783612/103442537-4ba67d00-4c57-11eb-9115-84214c44ecd3.png)

If this does not answer your point, please reopen the issue :-)
