### ISSUE TITLE
[CRASH] EXC_BAD_ACCESS (SIGSEGV) [Realm]

### ISSUE THREAD

**Issue by cargo11900** [AppTapp/Installer-Issues#110]
**Describe the crash**
Installer 5 seems to crash randomly. Sometimes while clicking on tweaks in side the app and sometimes while opening the app.

**To Reproduce**
Opening the app and clicking on random tweaks causes random crashing. Doesn’t seem to be anything in particular.

**Expected behavior**
App should open normally and load all repositories and in some cases load specific tweak information as would be normal operating function when clicking on a tweak.

**Screenshots**

**Device (please complete the following information):**
 - Device: iPhone 11
 - OS: iOS 13.3.1
 - Installer version 5.1
 - Jailbreak unc0ver

**Additional context**

**Crashlog -- REQUIRED** 

https://psty.io/p?q=a7fd9

**Comment by AppTapp** [comment]
Thank you for your report & crash log. It seems there is an issue with your database, did Installer reset your database when you Installed it?

**Comment by cargo11900** [comment]
Yes, it reset all my repositories and did a fresh install. Imported from Cydia.

**Comment by AppTapp** [comment]
> Yes, it reset all my repositories and did a fresh install. Imported from Cydia.
> […](#)

Interesting, I’ve asked our main developer to look at it. He’ll reply to this thread once he finds/fixes the issue. Thank you for the crash log!

**Comment by SynnyGR** [comment]
Hi @cargo11900 ,

Main developer here.
Thanks for your report and sorry for any inconveniences.

The crashlog you uploaded seems to have been deleted. Can you reupload it on pastebin for example ? 

Thanks in advance and have a nice day.

Regards

**Comment by SynnyGR** [comment]
Closed due to lack of response from user
