### ISSUE TITLE
[BUG] Local Backup not working

### ISSUE THREAD

**Issue by Charliefr3sh** [AppTapp/Installer-Issues#111]
**Describe the bug**
Installer does not create local backup, seems only to backup online as it needs an internet connection to backup. When you tap "Restore Backup", it says there's no local backup saved. The "local_backup.txt" file is also missing in Filza

**To Reproduce**
Steps to reproduce the behaviour:
Settings > Backup State > Backup now 

**Does the issue always occur when trying to reproduce it?** 
Yes

**Expected behavior**
Creating a local backup is expected

**Screenshots or videos**
![image](https://user-images.githubusercontent.com/60616091/103440247-9373d700-4c4c-11eb-84ee-9def2657d3f6.png)

**Device (please complete the following information):**
 - Installer version: [5.1-70]
 - iOS: [iOS 14.3, iPadOS 14.3]
 - Jailbreak: Checkra1n
 - Device [iPhone 8 Plus, iPad 6th Gen]

**Additional context**

**Comment by SynnyGR** [comment]
Hi,

The issue have been fixed, the fix should be available within the next beta.

Have a nice day.

Regards

**Comment by Charliefr3sh** [comment]
Bug still persists, it hasn't been fixed in the update
