### ISSUE TITLE
Inconsistent Design Language between Get buttons

### ISSUE THREAD

**Issue by mpelteshki** [AppTapp/Installer-Issues#114]
I believe it would make the whole experience more unified if the Get buttons had the same design language as the More button(a design similar to the Get buttons in the home tab).
![CEBB085E-24CB-4600-BC98-5AE3F6E7346E](https://user-images.githubusercontent.com/39273158/103445842-a9e85580-4c81-11eb-9ede-c729c222ed34.png)
![DCB8E801-312A-461D-8E02-B854DE149E2A](https://user-images.githubusercontent.com/39273158/103445851-aead0980-4c81-11eb-93a5-e2fe6089c200.png)

Here’s a concept of how this would look:

![8DFC9850-A509-4483-B0EA-51C4B22E8E84](https://user-images.githubusercontent.com/39273158/103445906-1b280880-4c82-11eb-9e81-ae97166217e4.png)
![27AD091B-F375-47B1-88C5-BAA8E241FD8C](https://user-images.githubusercontent.com/39273158/103445907-1ebb8f80-4c82-11eb-9de9-6d2fe047eea8.png)

Yesterday I posted pretty much the same issue, but I’m still pretty confused about why this can’t happen.

**Comment by SynnyGR** [comment]
This is a duplicate issue. As you may have have seen in your mail notifications, the issue about the get buttons have been fixed and the fix should be available in the next beta quickly.

Regards
