### ISSUE TITLE
Update/Modify button is cut off sometimes

### ISSUE THREAD

**Issue by jason5122** [AppTapp/Installer-Issues#117]
**Describe the bug**
The `Update`/`Modify` button text appears truncated sometimes.

**To Reproduce**
Steps to reproduce the behaviour:

1. Under `Changes`, select a tweak that has an update.
2. Often enough (unsure exact situation this occurs in), the button text will be cut off. If not, try with other tweak pages. This occurs with roughly half of my tweaks.

**Does the issue always occur when trying to reproduce it?** 
No

**Expected behavior**
The update button should appear as normal: without cut off text.

**Screenshots or videos**
Update cut off:
![image](https://user-images.githubusercontent.com/34594853/103464953-d645b580-4d05-11eb-9063-76df6af8dacd.png)

Modify cut off:
![image](https://user-images.githubusercontent.com/34594853/103465142-0fcaf080-4d07-11eb-92f6-3f02f64edc11.png)

Normal:
![image](https://user-images.githubusercontent.com/34594853/103465093-a814a580-4d06-11eb-8bdd-dd0386706466.png)

**Device (please complete the following information):**
 - Installer version: 5.1-70
 - iOS: 13.5
 - Jailbreak Checkra1n
 - Device iPhone X

**Comment by rastafaa** [comment]
I noticed this too

**Comment by AppTapp** [comment]
Thank you for your report, this will be worked on and should be fixed in the upcoming releases.

**Comment by SynnyGR** [comment]
Hi there,

This issue have just been fixed, the fix should be available in the next beta ;)

Have a nice day.

Regards
