### ISSUE TITLE
[SUGGESTION] Top 100 repos installed

### ISSUE THREAD

**Issue by DrFA** [AppTapp/Installer-Issues#12]
Installer has a great section to discover a bunch of repos, but a lot of them most ppl have never heard and a lot of repo are repeated (devs github, there beta repo etc..)

I was wonder if you can add a subcategory to help users discover new developers that are actually creating tweaks and themes for iOS 12/13 by adding a category like “top 100 repos of 2019” (change the idea however you like) but I think it would be an asset for installer to have something more targeted toward the devs creating tweaks for the current compatible jailbreaks

**Comment by AppTapp** [comment]
After the 5.1 redesign is complete, we will find a way to properly do this. Good suggestion :-)
