### ISSUE TITLE
[BUG] Data connection

### ISSUE THREAD

**Issue by Hermy-o** [AppTapp/Installer-Issues#120]
The error I have is that it does not connect to the internet when I install Installer, it just does not load repos or tweaks, I installed it from Sileo

The error occurred when entering Installer and wanting to add a repo or install a tweak

When I installed Sileo, I got a message to use Wi-Fi / mobile data or nothing but when I installed Installer I didn't get that message, I hope you can add that 

I have no screenshots or video of that, sorry

Installer 5.1 public beta 
 iOS 13.6
 Jailbreak Odyssey
 iPhone 11 64GB 

Some additional information is that my iPhone is from China and uses WLAN, so unlike other iPhone's is that when I install an app for the first time I get a message that if that app will use wifi wifi / mobile data or nothing I do not know that is due but in Installer it did not ask me that

**Comment by AppTapp** [comment]
Thank you for your report. Just to confirm, after you installed Installer did not work when you were connected to mobile data or WiFi? I'm trying to understand the issue :-)

**Comment by SynnyGR** [comment]
Closed due to lack of response from user
