### ISSUE TITLE
[BUG] Web Depictions from some sources don’t load

### ISSUE THREAD

**Issue by mpelteshki** [AppTapp/Installer-Issues#121]
**Describe the bug**
Opening a package depiction from, for example, procursus or samg_is_a_ninja’s repo, presents you with a blank screen.

![A44578CB-FB3D-49DC-8482-437AC63379F7](https://user-images.githubusercontent.com/39273158/103475463-0056b080-4db6-11eb-85c5-e1d73664e095.png)

**Does the issue always occur when trying to reproduce it?** 
Yes

**Device (please complete the following information):**
 - Installer version: [5.1-70]
 - iOS: [iOS 14.3]
 - Jailbreak [Odysseyra1n]
 - Device [iPhone 7]

**Comment by AppTapp** [comment]
Thank you for your report. The issue has been verified, and we will look into it and fix it in the upcoming builds.

**Comment by SynnyGR** [comment]
Hi there,

Thanks for your report. That's the normal behavior since the packages you are talking about doesn't have a depiction hosted on some website.
You can however change that behavior by going to the Settings > General and turn "Web Depiction as Fallback" off.

Have a nice day.

Regards
