### ISSUE TITLE
[BUG] See older packages overlapped by queue

### ISSUE THREAD

**Issue by dag0l** [AppTapp/Installer-Issues#124]
**Describe the bug**
A see older packages on changes is overlapped by queue tab

**To Reproduce**
Steps to reproduce the behaviour:
1. queue a tweak
2. refresh sources
3. scroll on changes tab till end
4. usually you get see older packages options, but it get overlapped by queue tab

**Does the issue always occur when trying to reproduce it?** 
Yes

**Expected behavior**
The see older packages should be above the queue tab

**Screenshots or video**
![ADF6A8C3-A87C-48A3-BA26-CFD1BA53FB72](https://user-images.githubusercontent.com/77109625/103900132-0805b480-512a-11eb-90b7-a809071c680f.png)

**Device (please complete the following information):**
 - Installer version: 5.1-70
 - iOS: iOS 13.6
 - Jailbreak: Odyssey 
 - Device: iPhone X

**Additional context**

**Comment by dag0l** [comment]
somehow not only the see older packages area that being overlapped, but everything that appear just about top of the navigation bar
![91000D5F-F876-4657-B160-590A1EDDE2D0](https://user-images.githubusercontent.com/77109625/103926850-1795f500-514c-11eb-8abf-ae959d6f6573.png)

**Comment by SynnyGR** [comment]
Hi there,

This issue have been fixed, the fix should be available in the next beta ;)

Have a nice day.

Regards
