### ISSUE TITLE
[SUGGESTION] Double Tap Tab icon to quickly go to the top of the tab

### ISSUE THREAD

**Issue by mpelteshki** [AppTapp/Installer-Issues#125]
I’d love it if Installer had a feature through which one could tap a certain tab from the tab bar’s icon once to go to the certain tab, and tap it once more to scroll to it’s top. I believe Installer 5.0 and Zebra have a similar feature implemented.

**Comment by SynnyGR** [comment]
Hi,

Thanks for your suggestion.
 This feature has been added to Installer and should be available with next beta ;)

have a nice day!

Regards
