### ISSUE TITLE
[SUGGESTION] Search Tab UI Suggestions

### ISSUE THREAD

**Issue by mpelteshki** [AppTapp/Installer-Issues#126]
1. I believe the page would look better if the search bar was aligned with the ‘big heading’ of the page, similar to how, for example, Zebra’s search bar and title are aligned.
 
![2E646535-EB61-4487-BC90-97D94ABBBD6B](https://user-images.githubusercontent.com/39273158/104588503-23644880-5671-11eb-8b5f-b6d26f74f2d6.png)
![3C72E529-E7C4-49C2-88A4-FFD1F0C7EB67](https://user-images.githubusercontent.com/39273158/104588512-252e0c00-5671-11eb-8cb7-1f9422ec4c4c.png)

2. I think the search bar feels a little empty right now and I believe that adding some text next to the search icon, again similar to how Zebra or Sileo have their ‘Search for Packages’-type text on their search bars
3. Lastly, i think the whole design of Installer would feel much more consistent if the search tab behaved the same way as the other tabs when scrolling down, and the big title and the search bar moved with the ‘most popular’ and ‘recent searches’ views.

https://user-images.githubusercontent.com/39273158/104589098-0d0abc80-5672-11eb-9900-29020687a08d.MP4

An example is how zebra does it:

https://user-images.githubusercontent.com/39273158/104589202-30356c00-5672-11eb-8a36-5c5a18200af9.MP4

**Comment by SynnyGR** [comment]
Hi,

The points 1 and 2 have been addressed and will be available in the next update.
As for the point , due to the nature of the view controller and the fact there is 4 different subviews in the search vc, it can't act as the other tabs.

Have a nice day!

Regards
