### ISSUE TITLE
[SUGGESTION] Source Sections and ‘Subsections’

### ISSUE THREAD

**Issue by mpelteshki** [AppTapp/Installer-Issues#128]
After going to a source’s page through the sources tab, there are sometimes sections where the packages are sorted by type. There are also sections that have other sections in them. 

https://user-images.githubusercontent.com/39273158/104713297-5ddeeb80-572c-11eb-88d3-6f29b8839369.MP4
For example the Tweaks written in bold from the video. I believe that everything would look cleaner if sections like that were removed, and instead we had just a list of all the subsections(similar to how sileo for example does it)

![85599647-7BBF-43B0-9785-BC5BB7DE5043](https://user-images.githubusercontent.com/39273158/104714110-78659480-572d-11eb-9e4b-3c12bb7ca3e8.png)

If you feel like removing it is a bad idea, could you at least make it so that it just shows it only when there’s more than one ‘subsection’ in it? Or add a preference to disable it?

**Comment by SynnyGR** [comment]
Hi,

Main Installer developper here.

Thanks for your suggestion.

This feature has been originally implemented to declutter the interface which result in a smoother experience globally.
However the suggestion you added at the end about removing that behavior if there is only one subsection is great, I'll work on it quickly.

Regards

**Comment by SynnyGR** [comment]
Your suggestion have just been added to Installer and should be available within the next beta ;)

Have a nice day!

Regards
