### ISSUE TITLE
[CRASH] When looking at tweak description after using the search function

### ISSUE THREAD

**Issue by DrFA** [AppTapp/Installer-Issues#13]
[installer.log](https://github.com/AppTapp/Installer-Issues/files/3976359/installer.log)
Read above

**Expected behavior**
Not crash

**Screenshots**

**Device (please complete the following information):**
 - Device: iPhone X
 - OS: iOS 13.3
 - Installer version Rc7
 - Jailbreak [e.g. Checkra1n]

**Additional context**

**Crashlog -- REQUIRED** 

https://pastebin.com/bzbQSnKU

**Comment by CreatureSurvive** [comment]
Possibly related to iOS 13.3, need to investigate further.
