### ISSUE TITLE
[SUGGESTION] Always make "Respring" button visible after installation done in console, instead of just "Respring Later"

### ISSUE THREAD

**Issue by yur1xpp** [AppTapp/Installer-Issues#131]
**Is your feature request related to a problem? Please describe.**
I noticed that the "Respring" button will not shows for packages that does not inject Springboard (needs verification on this), but surely for springboard tweaks. This sometimes not always the case, for example, injection into `backboardd` also virtually injecting into springboard, which also requires a respring. Dismissing the console and tap the respring now seems unnecessary and extra. In most cases, respring also effectively makes tweaks that inject into an app to take effect, which means repspring is almost a necessity for most situations.

**Describe the solution you'd like**
Always show "Respring" button for tweaks, except for tool packages, where there's no injection.

**Comment by vanwijkdave** [comment]
https://github.com/AppTapp/Installer-Issues/issues/130#issuecomment-773628398

**Comment by vanwijkdave** [comment]
Should be addressed by the optimisations I made today!
