### ISSUE TITLE
[SUGGESTION] Option to automatically respring whenever installation/removing tasks finished

### ISSUE THREAD

**Issue by yur1xpp** [AppTapp/Installer-Issues#132]
**Is your feature request related to a problem? Please describe.**
To be honest, this is one thing I really wish on Installer, as most of the times, installation and removing of tweaks requires respring, might as well just automatically do that.

**Describe the solution you'd like**
Adds an option in setting to allow auto respring after finished installation/removing for tweaks, but not tool packages.

**Comment by vanwijkdave** [comment]
Finished, will be available in the next beta. The option is called "Auto Respring" you will be able to enable it in the general tab.

**Comment by yur1xpp** [comment]
Thanks for taking the suggestion and the effort made into realize it :)
