### ISSUE TITLE
[SUGGESTION] Revert accidently tapped "Modify" button to its initial state when tapped

### ISSUE THREAD

**Issue by yur1xpp** [AppTapp/Installer-Issues#133]
**Is your feature request related to a problem? Please describe.**
Ability to reset tapped "Modify" button on the right side of tweak in "Installed" tab to its initial state ("Modify"). Current solution is to open the queue and manually remove them from there, quite a few taps to reach.

**Describe the solution you'd like**
Tap the changed state ("Queued" etc) of "Modify" button to reset to its initial state.

**Comment by AppTapp** [comment]
We will task about this suggestion with the rest of the team. For what it's worth, you can dismiss the queue by swiping it away to the left. I understand your suggestion is different but wanted to mention it anyway.

**Comment by SynnyGR** [comment]
Hi,

Your suggestion have just been added to Installer and should be available within the next beta ;)

Have a nice day!

Regards
