### ISSUE TITLE
[BUG][NOT SURE] Tapping the red cross in queue doesn't remove package from queue

### ISSUE THREAD

**Issue by yur1xpp** [AppTapp/Installer-Issues#134]
**Describe the issue**
I'm not sure is this a bug or intended design, where in the queue, tapping the red cross doesn't remove the queued package. Swiping them to the left and manually tap "Delete" did the job. From a user perspective, tapping the red cross should remove it from queue. Would like a confirmation from the team though.

**To Reproduce**
1. Open queue and tap the red cross

**Does the issue always occur when trying to reproduce it?**
Yes

**Expected behavior**
When tapped the red cross, remove the package from queue

**Device (please complete the following information):**
 - Device: [e.g. iPhone6] iPhone X
 - OS: 13.5
 - Version: 5.1-72
 - Jailbreak: unc0ver

**Additional context**

**DO NOT FORGET TO LABEL THIS REPORT**

**Comment by AppTapp** [comment]
The red cross is an icon to indicate that the package is being removed, it's not a button :-)
