### ISSUE TITLE
[CRASH]

### ISSUE THREAD

**Issue by FrogHoTT** [AppTapp/Installer-Issues#135]
**Describe the crash**
A clear description the crash

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device (please complete the following information):**
 - OS: [e.g. iOS 12.4]
 - Installer version [5.0 beta 9]
 - Jailbreak [e.g. Checkra1n]

**Additional context**

**Crashlog -- REQUIRED** 
Either upload the crashlog here or upload it to a service like psty.io

Go to install some app or anything else and it just shuts out.. 
iPhone 6
13.4
Uncover 
Newest installer software 

![8413FB1C-DD58-41C3-8622-4FDBD16DA2B9](https://user-images.githubusercontent.com/35989304/104986857-f98c8800-59c8-11eb-915d-36c15e08f1ab.png)

Then I get this and I have no idea how or where to go to fix it please help thank you

**Comment by vanwijkdave** [comment]
What tweak are you trying to install, and are you sure all correct repos are added for said tweak? The error tells you that the tweak/app you're trying to install depends on a specific fork of app sync, which It can't find. So maybe try removing that tweak or installing the dependency.

**Comment by SynnyGR** [comment]
Hi,

The console say that a dependency is half installed, you need to run the advised command in an app such as NewTerm to fix this.
Since this issue isn't related to Installer itself I'm going to close the issue.

Have a nice day!

Regards
