### ISSUE TITLE
[BUG] Connexion store Cydia

### ISSUE THREAD

**Issue by audris42** [AppTapp/Installer-Issues#136]
**Device (please complete the following information):**
 - Installer version: [e.g. 5.0RC3-1]
 - iOS: [14.3]
 - Jailbreak [Checkra1n]
 - Device [e.g. iPhone 7]

https://mega.nz/file/iIA0ibZT#51rkcZTY5VJqZ9VSahKZo5CWzc_WE5LF5PZplfgKF0A

**Comment by SynnyGR** [comment]
Hi,

As shown in the last portion in the video while you demoed it, Cydia experienced a server error.
This issue isn't reproductible as we speak.

Have a nice day!

Regards
