### ISSUE TITLE
[BUG] Installer hangs/crashes when opening General settings

### ISSUE THREAD

**Issue by TheProgramableTurtle** [AppTapp/Installer-Issues#137]
**Describe the bug**
When opening the General settings Installer hangs for a very long time until it opens the page. If any other part of the system (control centre, app switcher, etc) is interacted with while Installer hangs then it keeps hanging for a bit longer and crashes. No crash report is generated.

**To Reproduce**
Open Installer, click the profile button in the top right, scroll down and click General.

**Does the issue always occur when trying to reproduce it?** 
Yes

**Expected behavior**
The General settings page opens in less than a minute after clicking it and doesn’t crash.

**Screenshots or videos**
**Device (please complete the following information):**
 - Installer version: [5.1-72]
 - iOS: [iOS 13.4]
 - Jailbreak [Odyssey]
 - Device [iPhone 6S]

**Additional context**
Issue has existed since the first public beta of 5.1, I didn’t realise it hadn’t been reported yet.

**Comment by SynnyGR** [comment]
Hi,

This issue was due to an incorrectly named icon and isn't reproductible anymore in private builds.

Thanks for your feedback and have a nice day!

Regards

**Comment by TheProgramableTurtle** [comment]
Just upgraded to the latest public beta, the issue with opening the General settings is fixed but scrolling past the URL Schemes text has the exact same result: freeze, crash, no crash log. Was this what was fixed in private builds or should I make a new issue?

**Comment by TheProgramableTurtle** [comment]
Hmm, was able to reproduce it but without crashing the app and it unfreezing after ~30 seconds.
