### ISSUE TITLE
[SUGGESTION] Dependancies list?

### ISSUE THREAD

**Issue by mozbius** [AppTapp/Installer-Issues#141]
**Is your feature request related to a problem? Please describe.**

Some times uninstalled tweaks leave leftovers after bring uninstalled.  

**Describe the solution you'd like**

It would be nice to have an option to list individual tweak dependancies. That would allow to distinguish what is still needed and what is not. Right now there seems to be a mix bag list of library files that are not needed with libraries that I am fairly confident are still needed.

**Screenshots if available**
I have a picture of that mix bag I was referring to. 
![CAFD5FAC-6478-4CDC-ACB3-AD9E50039652](https://user-images.githubusercontent.com/54375590/106615887-e76b2780-653a-11eb-89df-4273bb79f121.png)

**Describe alternatives you've considered**
An alternative would be a cured list of library files that are not needed,

**Comment by SynnyGR** [comment]
Hi, 

Main Installer dev here.

This suggestion has been added to Installer just now and is going to be available in the next update.

Have a nice day!

Regards
