### ISSUE TITLE
[BUG] Tapping an icon from the tab bar, while already at the top of a page, applies an offset to the page

### ISSUE THREAD

**Issue by mpelteshki** [AppTapp/Installer-Issues#143]
Tapping an icon from the tab bar while already at the top of the page applies an offset to the whole page until its refreshed(until you switch to another tab and then back to the initial one)

https://user-images.githubusercontent.com/39273158/108365658-20282380-7200-11eb-963d-7e65583e1ef5.MP4

**Device (please complete the following information):**
 - Installer version: [5.1-74]
 - iOS: [iOS 14.4]
 - Jailbreak [Odysseyra1n ]
 - Device [iPhone 7]

**Comment by vanwijkdave** [comment]
Fixed!
