### ISSUE TITLE
[BUG] The interface options tab in settings has duplicated settings

### ISSUE THREAD

**Issue by mpelteshki** [AppTapp/Installer-Issues#144]
The interface options tab in installer’s settings has a set of settings duplicated.
![BEF74FD9-A079-4259-825A-BAA359674E7C](https://user-images.githubusercontent.com/39273158/108365974-80b76080-7200-11eb-8a73-acc1a1370cff.png)
![0B14267D-EE3C-48D8-9649-0700324DFA2D](https://user-images.githubusercontent.com/39273158/108365985-82812400-7200-11eb-8089-d0e07970afc8.png)

**Device (please complete the following information):**
 - Installer version: [5.1-74]
 - iOS: [iOS 14.4]
 - Jailbreak [Odysseyra1n ]
 - Device [iPhone 7]

**Comment by vanwijkdave** [comment]
Fixed!
