### ISSUE TITLE
[SUGGESTION] Allow for holding down on the UDID on the bottom of the home page to copy it

### ISSUE THREAD

**Issue by mpelteshki** [AppTapp/Installer-Issues#145]
I would love it if you could allow for holding down the UDID at the bottom of the home page to copy it. A feature like that was available in installer 5.0.
![289B8D84-3CC5-47CB-870A-7A561A885336](https://user-images.githubusercontent.com/39273158/108366366-f4f20400-7200-11eb-8f85-cf962171bc87.png)

**Comment by vanwijkdave** [comment]
Thou ask and thou shall receive https://imgur.com/a/UtlglnV
