### ISSUE TITLE
[BUG] Tweak depictions from some repos(notably Alfhaily APT) show the wrong tint colors

### ISSUE THREAD

**Issue by mpelteshki** [AppTapp/Installer-Issues#146]
Tweaks from Alfhaily APT(notably rocket for instagram and cercube for youtube)’s tint colors show up as black in installer, while in sileo they show up as their intended colors(aka orange for rocket and red for cercube).

![9A4CBBC7-0DE9-497C-9E9E-ADCBF3F8E24F](https://user-images.githubusercontent.com/39273158/108366991-a4c77180-7201-11eb-9fe6-c68484c40275.png)
![D89C4D5C-D5D6-4094-AE8D-1CE2C57DCA70](https://user-images.githubusercontent.com/39273158/108367010-a8f38f00-7201-11eb-87cf-00344e2ced3d.png)

**Device (please complete the following information):**
 - Installer version: [5.1-74]
 - iOS: [iOS 14.4]
 - Jailbreak [Odysseyra1n ]
 - Device [iPhone 7]

**Comment by vanwijkdave** [comment]
Fixed!
