### ISSUE TITLE
[SUGGESTION] Allow for setting URL schemes, not only by tapping the blue circle below the icon of the package managers, but also by tapping the icon of the respective package manager

### ISSUE THREAD

**Issue by mpelteshki** [AppTapp/Installer-Issues#147]
With the current implementation where you have to tap into the small circle to enable a specific url scheme, it can be challenging to actually tap the circle and not the area around it. I also think that adding a little check mark in the circles whenever an url scheme is active would make it look much more clean.
![A0976750-D366-432E-98E4-5D0BEB5EB1AD](https://user-images.githubusercontent.com/39273158/108367685-6088a100-7202-11eb-820b-9f1a65ef3291.png)

**Device (please complete the following information):**

 - Installer version: [5.1-74]
 - iOS: [iOS 14.4]
 - Jailbreak [Odysseyra1n ]
 - Device [iPhone 7]

**Comment by vanwijkdave** [comment]
Images are now tappable! Thanks for the suggestion (as always ;)
