### ISSUE TITLE
[BUG]Installer backups only backup repos, not packages

### ISSUE THREAD

**Issue by mpelteshki** [AppTapp/Installer-Issues#148]
After making a backup through installer, I can see i that only the sources I had are available to restore, and not the packages.
![C9996A1F-F30B-462C-95AA-F20575C009EB](https://user-images.githubusercontent.com/39273158/108368147-cb39dc80-7202-11eb-9bb1-90b829402614.png)

**Device (please complete the following information):**
 - Installer version: [5.1-74]
 - iOS: [iOS 14.4]
 - Jailbreak [Odysseyra1n ]
 - Device [iPhone 7]

**Comment by vanwijkdave** [comment]
Will be added next update :)
