### ISSUE TITLE
[BUG] After installing some packages, they get stuck at ‘Working’ even when the verbose window says everything is done

### ISSUE THREAD

**Issue by mpelteshki** [AppTapp/Installer-Issues#149]
A lot of packages get stuck at ‘Working’ whenever you install or uninstall them, even if the verbose window says all tasks are done.

![D4AB21E2-D007-4655-AE33-0818E6276E63](https://user-images.githubusercontent.com/39273158/108369506-549dde80-7204-11eb-809a-5475f61d94e0.png)

**Device (please complete the following information):**
 - Installer version: [5.1-74]
 - iOS: [iOS 14.4]
 - Jailbreak [Odysseyra1n ]
 - Device [iPhone 7]

**Comment by vanwijkdave** [comment]
Fixed, thanks again for reporting!
