### ISSUE TITLE
[BUG] ‘Restore your saved Installer setup’ button makes a new backup rather than restoring an old one

### ISSUE THREAD

**Issue by mpelteshki** [AppTapp/Installer-Issues#15]
Going to the settings page and tapping the ‘backup your installer setup’ button does work as expected. The ‘restore saved installer setup’ button though doesn’t restore it but rather makes another backup.

**Does the issue always occur when trying to reproduce it?** 
Yes

I expect for it to restore the setup and not make a new backup

**Device (please complete the following information):**
 - Installer version: [5.0RC8]
 - iOS: [iOS 13.3]
 - Jailbreak [Checkra1n]
 - Device [iPhone 7]

**Comment by CreatureSurvive** [comment]
This is fixed in the upcoming version, setup restoration is now fully working again.
