### ISSUE TITLE
[BUG] Packages don’t always get queued when tapping the ‘remove unneeded packages’ button

### ISSUE THREAD

**Issue by mpelteshki** [AppTapp/Installer-Issues#150]
When tapping the ‘remove unneeded packages button, packages don’t always get queued for removal.

https://user-images.githubusercontent.com/39273158/108370104-f6253000-7204-11eb-9516-2b7901c49700.MP4

**Device (please complete the following information):**
 - Installer version: [5.1-74]
 - iOS: [iOS 14.4]
 - Jailbreak [Odysseyra1n ]
 - Device [iPhone 7]

**Comment by SynnyGR** [comment]
Hi there,

Sorry for the late reply.
This issue have just been fixed, the fix should be available in the update that will be released quickly.

Have a nice day.

Best regards
