### ISSUE TITLE
[BUG] Settings page offset

### ISSUE THREAD

**Issue by mpelteshki** [AppTapp/Installer-Issues#153]
After entering the settings page of Installer, the page isn’t scrolled to the top.

https://user-images.githubusercontent.com/39273158/108589184-e40ed300-7365-11eb-82d0-a0ab99c1663a.MP4

**Device (please complete the following information):**
 - Installer version: [ 5.1-74]
 - iOS: [iOS 14.4]
 - Jailbreak [Odysseyra1n]
 - Device [iPhone 7]

**Comment by vanwijkdave** [comment]
Fixed
