### ISSUE TITLE
[BUG] Glitch in switching between light and dark more

### ISSUE THREAD

**Issue by mpelteshki** [AppTapp/Installer-Issues#154]
When switching the system settings for light and dark mode while in installer, not every part of the app switches appearance right away:

https://user-images.githubusercontent.com/39273158/108589273-54b5ef80-7366-11eb-9ebd-282c72703d13.MP4

**Device (please complete the following information):**
 - Installer version: [ 5.1-74]
 - iOS: [iOS 14.4]
 - Jailbreak [Odysseyra1n]
 - Device [iPhone 7]

**Comment by SynnyGR** [comment]
Hi there,

This issue has just been fixed. A new update should come soon including this fix.

Have a nice day.

Best regards
