### ISSUE TITLE
[BUG] Scrolling isn’t particularly smooth in the home, changes, sources, and installed tabs

### ISSUE THREAD

**Issue by mpelteshki** [AppTapp/Installer-Issues#155]
Scrolling down while in any of Installer’s tabs is often filled with a lot of stuttering.

https://user-images.githubusercontent.com/39273158/108589456-02290300-7367-11eb-8408-1be8f1c9921e.mov

**Device (please complete the following information):**
 - Installer version: [5.1-74]
 - iOS: [iOS 14.4]
 - Jailbreak [Odysseyra1n]
 - Device [iPhone 7]

**Comment by SynnyGR** [comment]
Hi there,

Scrolling performance have been improved lately, a new version should be released soon with the fix.

Have a nice day.

Best regards
