### ISSUE TITLE
[BUG] Auto Respring stops Remove Unnecessary Packages

### ISSUE THREAD

**Issue by NickoTheDev** [AppTapp/Installer-Issues#157]
**Describe the bug**
After removing a tweak, if there are unnecessary packages left, you are prompted with a button to add them to a remove queue. If you have Auto Respring enabled with a delay, the countdown continues after clicking the button and resprings before you are able to remove the packages.

**To Reproduce**
1. Enable Auto Respring with a delay
2. Remove a package that results in packages becoming unnecessary
3. When you try removing them, the device will continue the respring countdown

**Does the issue always occur when trying to reproduce it?** 
Yes

**Expected behavior**
The Auto Respring should be cancelled.

**Screenshots or videos**
https://user-images.githubusercontent.com/69074764/109425289-38622480-79f0-11eb-9194-85fc41e09e2f.MP4

**Device (please complete the following information):**
 - Installer version: 5.1-74
 - iOS: iOS 14.3
 - Jailbreak: unc0ver
 - Device: iPhone 11 Pro Max

**Comment by vanwijkdave** [comment]
Good idea! It now automatically disables the auto respring in instances where unneeded packages are found!
