### ISSUE TITLE
[BUG] Error 303, operation can’t complete

### ISSUE THREAD

**Issue by rastafaa** [AppTapp/Installer-Issues#159]
**Describe the bug**
Attempting to update tweaks.. operation fails with error and aborts

**To Reproduce**
Steps to reproduce the behaviour: select tweaks to update and begin updating

**Does the issue always occur when trying to reproduce it?** 
Not sure yet

**Expected behavior**
Successful update and respiring

**Screenshots or videos**
![359D7C51-FB07-4514-A4B9-56EFB683D99E](https://user-images.githubusercontent.com/37600342/109735633-f106a000-7b77-11eb-9b58-60b5e6a62ae1.png)

**Device (please complete the following information):**
 - Installer version: 5.1 (latest release)
 - iOS: 13.5
 - Jailbreak unc0ver
 - Device iPhone X

**Additional context**
Has started to happen repeatedly. Also get crash if I pull down to refresh updates page. When restarting installer some tweaks needing updates no longer appear,  unclear if they were successfully updated

**Comment by rastafaa** [comment]
On attempting to update the tweaks again, I find that installer has deleted some of them. I have to reinstall now

**Comment by SynnyGR** [comment]
Hi there,

This issue usually means that the response sent from the server can't be parsed (server side issue or communication with your device issue).
As for the update issue you are talking about it has been fixed yesterday, the fix should be available within the next release.

Best regards
