### ISSUE TITLE
[BUG] Installer Crashes when installing purchased tweaks

### ISSUE THREAD

**Issue by CreepsterTCM** [AppTapp/Installer-Issues#16]
**Describe the bug**
Installer Crashes when trying to install or update any purchased tweaks

**To Reproduce**
Literally try to install any purchased tweak

**Does the issue always occur when trying to reproduce it?** 
Yes

**Expected behavior**
The tweak should install as smooth as others 

**Screenshots or videos**
Attached :)

**Device (please complete the following information):**
 - Installer version: 5.0 RC 8
 - iOS: 12.4
 - Jailbreak: Unc0ver 
 - Device: IPhone 7+

**Additional context**

https://psty.io/p?q=2d17a
Crash Report

**Comment by CreepsterTCM** [comment]
[Proof](https://youtu.be/S0P3AgKSWEY) here is video proof

**Comment by CreatureSurvive** [comment]
Thanks for reporting this. We have fixed this issue in the update we are working on.
