### ISSUE TITLE
[CRASH] Swipe to uninstall package

### ISSUE THREAD

**Issue by Colaski** [AppTapp/Installer-Issues#160]
**Describe the crash**
Clicking uninstall when swiping on installed package to remove causes crash

**To Reproduce**
Navigate to “Installed” tab, swipe on a package and click “Uninstall”.

**Expected behavior**
Add package to queue for removal.

**Screenshots**
![9A05A905-5A67-48B4-B182-535AF89B7BEC](https://user-images.githubusercontent.com/79936742/109847398-fe696c00-7c03-11eb-9a72-cb679538fbd1.jpeg)

**Device (please complete the following information):**
 - Device: iPhone XS
 - OS: iOS 14.3
 - Installer version 5.1-74
 - Jailbreak Unc0ver 6.0.1

**Crashlog** 
https://pastebin.com/4TAkeTGh

**Comment by vanwijkdave** [comment]
fixed
