### ISSUE TITLE
[BUG] Backup-Restore

### ISSUE THREAD

**Issue by Colaski** [AppTapp/Installer-Issues#161]
**Describe the bug**
Installer 5.0 allowed for restores and backups on-device. When pressing "Backup State" on the 5.1 beta I get a message telling me it will be stored on server (installer 5.0 says server is Patreon only and gives option for on-device). Pressing the "Backup Now" button gives a success message. When pressing "Restore Backup" I get "No local backups were found, and you are not signed in to access server backups" (I am signed in).

**To Reproduce**
Backup and restore

**Does the issue always occur when trying to reproduce it?** 
Yes

**Expected behavior**
Write a file on-device for backing up, restore to read from that file and restore.

**Screenshots or videos**
![image](https://user-images.githubusercontent.com/79936742/109852010-2d361100-7c09-11eb-8c4d-bf834767e254.png)
![image](https://user-images.githubusercontent.com/79936742/109852173-5b1b5580-7c09-11eb-8c58-3a4d2d5489d9.png)
![image](https://user-images.githubusercontent.com/79936742/109852211-653d5400-7c09-11eb-83a4-1d2e05d48e4c.png)
**Device (please complete the following information):**
 - Installer version: 5.1-74
 - iOS: iOS 14.3
 - Jailbreak Unc0ver 6.0.1
 - Device iPhone XS

**Comment by SynnyGR** [comment]
Hi there,

Local backups have been fixed previously, this issue shouldn't happen anymore.


Best regards
