### ISSUE TITLE
[CRASH]

### ISSUE THREAD

**Issue by ghost** [AppTapp/Installer-Issues#164]
**Describe the crash**
A clear description the crash

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device (please complete the following information):**
 - Device: [e.g. iPhone6] iPhone XR
 - OS: [e.g. iOS 12.4] 14.3
 - Installer version [5.0 beta 9] 5.1
 - Jailbreak [e.g. Checkra1n] Unc0ver 

**Additional context**

**Crashlog -- REQUIRED** 
Either upload the crashlog here or upload it to a service like psty.io

https://we.tl/t-HjuMb3OHtl

**Comment by vanwijkdave** [comment]
need more context, + the link expired. Please use a site like  [psty.io](psty.io)

**Comment by ghost** [comment]
Sorry about that I used FutureRestore. I don't have logs anyway I don't using anymore switched to Taurine
