### ISSUE TITLE
[CRASH]

### ISSUE THREAD

**Issue by Aahil52** [AppTapp/Installer-Issues#165]
**Describe the crash
App crashes when trying to view any tweak from skitty’s repo with a few exceptions

**To Reproduce**
Add and open skitty’s repo
Attempt to view on of the tweaks (for example: ersatz) (a few tweaks are an exception)

**Expected behavior**
Show the tweak // no crash

**Screenshots**

**Device (please complete the following information):**
 - Device: iPhone 11 Pro
 - OS: iOS 14.2
 - Installer version: 5.1 beta
 - Jailbreak: unc0ver

**Additional context**

**Crashlog -- REQUIRED** 
Either upload the crashlog here or upload it to a service like psty.io
https://pastebin.com/TVNNnB81

**Comment by vanwijkdave** [comment]
Found cause, will continue trying to fix the crash

**Comment by vanwijkdave** [comment]
The issue was that it took the version number as an Integer, and tried to put in in a string, which resulted in a crash. It now checks if the data is a string, and if it isn't it'll try to convert the value of it to one. 

Works perfectly fine again 👌🏻 https://imgur.com/a/1TxVDno
