### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Aahil52** [AppTapp/Installer-Issues#166]
**Describe the bug**
The interface customization options are repeated

**To Reproduce**
go to the interface options menu

**Does the issue always occur when trying to reproduce it?** 
Yes; this behavior is present on both my phone and my iPad

**Expected behavior**
Interface customization options only displayed once.

**Screenshots or videos**
If applicable, add screenshots or videos to help explain your problem.

**Device (please complete the following information):**
 - Installer version: 5.1 beta
 - iOS: 14.2
 - Jailbreak: unc0ver
 - Device: iPhone 11 pro

https://user-images.githubusercontent.com/32886850/111570479-544d2080-877b-11eb-81c0-80e55507dd3e.MP4

**Additional context**

**Comment by vanwijkdave** [comment]
Fixed! :)
