### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Ortaiga** [AppTapp/Installer-Issues#169]
**Stores Login**
Cydia store page doesn’t open. 

**To Reproduce**
Open stores, click on Cydia store login. The page won’t show anything:

**Does the issue always occur when trying to reproduce it?** 
Yes

**Expected behavior**
The page to open!

**Screenshots or videos**
If applicable, add screenshots or videos to help explain your problem.

**Device (please complete the following information):**
 - Installer version: [5]
 - iOS: [ iOS 14.0.1 ]
 - Jailbreak [Unc0ver]
 - Device [iPhone X]

**Comment by vanwijkdave** [comment]
Already fixed internally, an update will be available shortly 🙂
