### ISSUE TITLE
[BUG] Crash while refreshing sources

### ISSUE THREAD

**Issue by Greigh** [AppTapp/Installer-Issues#17]
**Describe the bug**
Crash when refreshing sources. 

**To Reproduce**
Steps to reproduce the behavior
Open app and refresh sources. 

**Does the issue always occur when trying to reproduce it?** 
No

**Expected behavior**

Refresh with no crashes. 

**Screenshots or videos**
If applicable, add screenshots or videos to help explain your problem.

**Device (please complete the following information):**
 - Installer version: 5.0 rc9
 - iOS: 12.4
 - Jailbreak: u0
 - Device: XS Max

https://ghostbin.co/paste/ah4uk

**Comment by CreatureSurvive** [comment]
Fixed in RC10
