### ISSUE TITLE
[BUG] No setting to change language manually

### ISSUE THREAD

**Issue by CloneVince** [AppTapp/Installer-Issues#170]
**Describe the bug**
No setting to change language manually

**To Reproduce**
Try to change manually language 😉 

**Does the issue always occur when trying to reproduce it?** 
Yes

**Expected behavior**
Having a setting to change language as in Installer 5.0

**Device (please complete the following information):**
 - Installer version: 5.1-74
 - iOS: 14.3
 - Jailbreak: Taurine
 - Device: XS Max

**Comment by vanwijkdave** [comment]
Added!
