### ISSUE TITLE
[BUG] Not installing/Uninstalling apps properly

### ISSUE THREAD

**Issue by Garydunlop00** [AppTapp/Installer-Issues#173]
**Describe the bug**
A clear and concise description of what the bug is. Installer 5.1 beta does not install or uninstall apps properly such as Sileo BETA, Zebra BETA or Filza

**To Reproduce**
Steps to reproduce the behaviour:
Try install or uninstall any of the apps mentioned, Or contact and I will provide a video of the bug.

**Does the issue always occur when trying to reproduce it?** 
For me yes.

**Expected behavior**
App should install or uninstall properly.

**Screenshots or videos**
If applicable, add screenshots or videos to help explain your problem.

https://imgur.com/a/QBfx5Qp

**Device (please complete the following information):**
 - Installer version: 5.1-74
 - iOS: IOS 14.2 and IOS 14.4.2
 - Jailbreak: OdysseyRa1n
 - Device: iPhone X

**Additional context**

**Comment by SynnyGR** [comment]
Hi, 

Managements of post install actions have just been changed. The issue shouldn't happen anymore however if you still face it with coming build I'll let you reopen the issue.

Best regards
