### ISSUE TITLE
[CRASH]

### ISSUE THREAD

**Issue by CySxL** [AppTapp/Installer-Issues#174]
**Describe the crash**
Immediately crash at launch if the system bold text is enabled.

**To Reproduce**
Go to Setting -> Screen Display and Brightness -> enable "Bold text"

Then try to launch Installer. 

**Expected behavior**
Don't crash while user is using Bold Text.

**Screenshots**
![image](https://user-images.githubusercontent.com/15531137/114128259-8ee74a80-992e-11eb-89f9-b176268a642e.png)

**Device (please complete the following information):**
 - Device: [iPhoneX]
 - OS:  [iOS 14.3]
 - Installer version [5.1-74]
 - Jailbreak [Taurine]

**Additional context**

**Crashlog -- REQUIRED** 

![image](https://user-images.githubusercontent.com/15531137/114128462-fe5d3a00-992e-11eb-8b90-c604a6880638.png)

**Comment by vanwijkdave** [comment]
Found a fix, will be patched next update!
