### ISSUE TITLE
[CRASH] When loading WhoozItPro package page

### ISSUE THREAD

**Issue by sadalhayat** [AppTapp/Installer-Issues#177]
**Describe the crash**
App crashes when loading WhoozItPro package page from repo http://apt.iarrays.com/

**To Reproduce**
1. Add repo http://apt.iarrays.com/
2. Open WhoozItPro package page from package list or search result and wait.

**Expected behavior**
WhoozItPro package depiction fully-loaded

**Video**
https://telegra.ph/file/8d9ec14a466f7c4ba36d7.mp4

**Device**
 - Device: iPhone XS
 - OS: iOS 14.3
 - Installer version: 5.0.3 stable
 - Jailbreak: Taurine 1.0.3

**Additional context**
The crash also reproduced on Safe Mode.

**Crashlog -- REQUIRED** 
https://pastebin.com/wUJbkuKN

**Comment by vanwijkdave** [comment]
Should be solved in next update, if not feel free to open this issue!
