### ISSUE TITLE
[CRASH] apt-get crashing when opening the Installer app

### ISSUE THREAD

**Issue by Shaq234** [AppTapp/Installer-Issues#178]
**Describe the crash**
A clear description the crash:
Just having Cr4shed notification of apt-get crashing when opening Installer

**To Reproduce**
Don’t know how reproduce it because it happens usually

**Expected behavior**

**Screenshots**

**Device (please complete the following information):**
 - Device: [iPhone 8 Plus]
 - OS: [iOS 14.3]
 - Installer version [5.1]
 - Jailbreak [Taurine 1.0.4]

**Additional context**
Add any other context about the problem here:

**Crashlog -- REQUIRED** 
Date: 4/18/21, 5:09 PM
Process: apt-get
Bundle id: (null)
Device: iPhone 8 Plus, iOS 14.3

Exception type: EXC_BAD_ACCESS (SIGSEGV)
Exception subtype: KERN_INVALID_ADDRESS: 0x106858000
Exception codes: 0x0000000000000001, 0x0000000106858000
Culprit: Unknown
VM Protection: 0x106858000 is not in any region.

Triggered by thread: 0
Thread name: Dispatch queue: com.apple.main-thread
Call stack:
0   libapt-private.0.0.dylib      	0x000000010261853c 0x1025f8000 + 132412     	// DoInstall(CommandLine&)
1   libapt-private.0.0.dylib      	0x00000001026184d8 0x1025f8000 + 132312     	// DoInstall(CommandLine&)
2   libapt-pkg.6.0.dylib          	0x0000000102847644 0x1027d0000 + 489028     	// CommandLine::DispatchArg(CommandLine::Dispatch const*, bool)
3   libapt-private.0.0.dylib      	0x000000010260cac4 0x1025f8000 + 84676      	// DispatchCommandLine(CommandLine&, std::__1::vector<CommandLine::Dispatch, std::__1::allocator<CommandLine::Dispatch> > const&)
4   apt-get                       	0x00000001025a7274 0x1025a0000 + 29300      	// main
5   libdyld.dylib                 	0x00000001a1b42568 0x1a1b41000 + 5480       	// start

Register values:
PC: 0x0                 LR: 0x0                 CPSR: 0x0
x0: 0x0                 x1: 0x0                 x2: 0x0
x3: 0x0                 x4: 0x0                 x5: 0x0
x6: 0x0                 x7: 0x0                 x8: 0x0
x9: 0x0                 x10: 0x0                x11: 0x0
x12: 0x0                x13: 0x0                x14: 0x0
x15: 0x0                x16: 0x0                x17: 0x0
x18: 0x0                x19: 0x0                x20: 0x0
x21: 0x0                x22: 0x0                x23: 0x0
x24: 0x0                x25: 0x0                x26: 0x0
x27: 0x0                x28: 0x0

Loaded images:
0: /usr/bin/apt-get
1: /usr/lib/pspawn_payload-stg2.dylib
2: /usr/lib/libapt-private.0.0.dylib
3: /usr/local/lib/liblzma.5.dylib
4: /usr/lib/liblz4.1.dylib
5: /usr/lib/libxxhash.0.dylib
6: /usr/lib/dyld
7: /usr/lib/libapt-pkg.6.0.dylib
8: /usr/lib/libzstd.1.dylib
9: /usr/lib/libgcrypt.20.dylib
10: /usr/lib/libgpg-error.0.dylib
11: /usr/lib/libintl.8.dylib
12: /usr/lib/system/libdispatch.dylib
13: /usr/lib/system/libdyld.dylib
14: /usr/lib/libicucore.A.dylib
15: /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation
16: /System/Library/Frameworks/SystemConfiguration.framework/SystemConfiguration
17: /System/Library/Frameworks/CFNetwork.framework/CFNetwork
18: /usr/lib/libnetwork.dylib
19: /System/Library/Frameworks/Foundation.framework/Foundation
20: /System/Library/Frameworks/Security.framework/Security
21: /usr/lib/system/libsystem_info.dylib
22: /usr/lib/system/libsystem_c.dylib
23: /System/Library/Frameworks/IOKit.framework/Versions/A/IOKit
24: /usr/lib/libMobileGestalt.dylib
25: /usr/lib/system/libsystem_malloc.dylib
26: /usr/lib/system/libsystem_networkextension.dylib
27: /usr/lib/libobjc.A.dylib
28: /usr/lib/libc++.1.dylib
29: /usr/lib/libc++abi.dylib
30: /System/Library/PrivateFrameworks/CoreAutoLayout.framework/CoreAutoLayout
31: /usr/lib/system/libsystem_trace.dylib
32: /usr/lib/libsqlite3.dylib
33: /usr/lib/system/libsystem_notify.dylib
34: /usr/lib/system/libcorecrypto.dylib
35: /usr/lib/system/libsystem_asl.dylib
36: /System/Library/PrivateFrameworks/IOMobileFramebuffer.framework/IOMobileFramebuffer
37: /System/Library/Frameworks/IOSurface.framework/IOSurface
38: /usr/lib/system/libsystem_symptoms.dylib
39: /usr/lib/system/libsystem_kernel.dylib
40: /usr/lib/libSystem.B.dylib
41: /usr/lib/libarchive.2.dylib
42: /System/Library/PrivateFrameworks/SoftLinking.framework/SoftLinking
43: /usr/lib/libCRFSuite.dylib
44: /usr/lib/libapple_nghttp2.dylib
45: /usr/lib/libbsm.0.dylib
46: /usr/lib/libbz2.1.0.dylib
47: /usr/lib/libcharset.1.dylib
48: /usr/lib/libcompression.dylib
49: /usr/lib/libcoretls.dylib
50: /usr/lib/libcoretls_cfhelpers.dylib
51: /usr/lib/libdns_services.dylib
52: /usr/lib/libenergytrace.dylib
53: /usr/lib/libiconv.2.dylib
54: /usr/lib/liblangid.dylib
55: /usr/lib/liblzma.5.dylib
56: /usr/lib/libpcap.A.dylib
57: /usr/lib/libresolv.9.dylib
58: /usr/lib/libutil.dylib
59: /usr/lib/libxml2.2.dylib
60: /usr/lib/libz.1.dylib
61: /usr/lib/system/libcache.dylib
62: /usr/lib/system/libcommonCrypto.dylib
63: /usr/lib/system/libcompiler_rt.dylib
64: /usr/lib/system/libcopyfile.dylib
65: /usr/lib/system/liblaunch.dylib
66: /usr/lib/system/libmacho.dylib
67: /usr/lib/system/libremovefile.dylib
68: /usr/lib/system/libsystem_blocks.dylib
69: /usr/lib/system/libsystem_collections.dylib
70: /usr/lib/system/libsystem_configuration.dylib
71: /usr/lib/system/libsystem_containermanager.dylib
72: /usr/lib/system/libsystem_coreservices.dylib
73: /usr/lib/system/libsystem_darwin.dylib
74: /usr/lib/system/libsystem_dnssd.dylib
75: /usr/lib/system/libsystem_featureflags.dylib
76: /usr/lib/system/libsystem_m.dylib
77: /usr/lib/system/libsystem_platform.dylib
78: /usr/lib/system/libsystem_product_info_filter.dylib
79: /usr/lib/system/libsystem_pthread.dylib
80: /usr/lib/system/libsystem_sandbox.dylib
81: /usr/lib/system/libunwind.dylib
82: /usr/lib/system/libxpc.dylib

{"ProcessBundleID":"","ProcessName":"apt-get","Culprit":"Unknown"}

**Comment by SynnyGR** [comment]
Hi,

That is strange but I believe this was due to an issue with an old version of apt-get which isn't part of Installer itself.
Since the issue doesn't happen anymore (at least in our testing) I'll close this issue and let you open one if it happen again with new versions.

Have a nice day.

Regards
