### ISSUE TITLE
[BUG] Hidden navbar when swiping back and cancelling the gesture 

### ISSUE THREAD

**Issue by PatrikTheDev** [AppTapp/Installer-Issues#18]
**Description of the bug**
The navbar in settings gets hidden if you begin to swipe back but you cancel that gesture

**To Reproduce**
Swipe back in settings but cancel it (swipe back to home view)

**Does the issue always occur when trying to reproduce it?** 
Yes

**Screenshots or videos**
![0480B3B5-3419-4219-BA40-E3056475538E](https://user-images.githubusercontent.com/25883885/72261303-d8a29180-3614-11ea-9152-c6c7cbfe8549.png)

**Device:**
 - Installer version: 5.0RC12-3
 - iOS: iOS 13.3
 - Jailbreak: Checkra1n
 - Device: iPhone X

**Comment by CreatureSurvive** [comment]
Thanks for reporting this, I keep forgetting to fix it because I’m usually in the process of fixing something else when this occurs. I will look into this soon though.

**Comment by CreatureSurvive** [comment]
Fixed in RC12-X
