### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by gitgud191** [AppTapp/Installer-Issues#180]
**Describe the bug**
After updating Installer to 5.1-85 my sources disappeared besides the defaults. I then copied them from Cydia and when I added them back they were all empty, but otherwise the repos were there. Then I tried downgrading and the problem persists. What could be the issue?

**To Reproduce**
Update to latest version? It’s possible that’s not the reason though I’m really not sure.

**Does the issue always occur when trying to reproduce it?** 
Yes

**Expected behavior**
I guess I just expected my sources to be there and contain their packages

**Screenshots or videos**

https://user-images.githubusercontent.com/35815645/119291758-d33f5900-bc03-11eb-85a5-f0828c5d11b1.mov

**Device (please complete the following information):**
 - Installer version: [5.1-85] (Downgrading did not solve the issue though)
 - iOS: [iOS 14.3]
 - Jailbreak [unc0ver 6.1.2]
 - Device [iPhone 12 Mini]

**Additional context**
This happened immediately upon updating Installer. Tried multiple older versions and sources just seem broken.

**Comment by BitGrub** [comment]
I have the issue. Also, when I imported 100+ sources from Zebra because Installer deleted the ones I had, all sources now show 0 packages (they still appear in search though)

**Comment by BitGrub** [comment]
Ever since the update I can't install any tweaks either

**Comment by vanwijkdave** [comment]
This is a known issue, we know what it is caused by. However, it's a hard issue to resolve. Downgrading to the last working version seems to do the trick!

**Comment by SynnyGR** [comment]
Hello,

Sorry for the inconveniences.
This issue was caused by a database upgrade issue that have been fixed previously.
You should not have this issue anymore. However if it happens again I'll let you reopen an issue with the same details level.

Have a nice day.

Best regards
