### ISSUE TITLE
[BUG] Update tag doesn’t get reset

### ISSUE THREAD

**Issue by mozbius** [AppTapp/Installer-Issues#182]
**Describe the bug**
Installer shows that the shshd package has an update available but yet when the update is applied the update is still showing as available as an update.

**To Reproduce**
Steps to reproduce the behaviour is to simply install shshd and the close and kill installer and reopen Installer to see the notification tag remain to 1.

**Does the issue always occur when trying to reproduce it?** 
Yes

**Expected behavior**
Notification tag should disappear reset once updates are applied.

**Screenshots or videos**

[url=https://ibb.co/dmbf57J][img]https://i.ibb.co/wcJdzYr/B6945-F30-8730-46-C3-A59-E-3-F5680-FE4-A32.png[/img][/url]

**Device (please complete the following information):**
 - Installer version: latest version as of june 8th 2021
 - iOS: 14.3
 - Jailbreak : Taurine 1.0.2, 1.0.4 (presumably 1.0.5 but Taurine results in a lot of BSOD)
 - Device: iPhone 7

**Additional context**
Sileo doesn’t show shshd as an available update even after a few days

**Comment by lafi-99** [comment]
> **Describe the bug**
> 
> Installer shows that the shshd package has an update available but yet when the update is applied the update is still showing as available as an update.
> 
> 
> 
> **To Reproduce**
> 
> Steps to reproduce the behaviour is to simply install shshd and the close and kill installer and reopen Installer to see the notification tag remain to 1.
> 
> 
> 
> **Does the issue always occur when trying to reproduce it?** 
> 
> Yes
> 
> 
> 
> **Expected behavior**
> 
> Notification tag should disappear reset once updates are applied.
> 
> 
> 
> **Screenshots or videos**
> 
> 
> 
> [url=https://ibb.co/dmbf57J][img]https://i.ibb.co/wcJdzYr/B6945-F30-8730-46-C3-A59-E-3-F5680-FE4-A32.png[/img][/url]
> 
> 
> 
> 
> 
> **Device (please complete the following information):**
> 
>  - Installer version: latest version as of june 8th 2021
> 
>  - iOS: 14.3
> 
>  - Jailbreak : Taurine 1.0.2, 1.0.4 (presumably 1.0.5 but Taurine results in a lot of BSOD)
> 
>  - Device: iPhone 7
> 
> 
> 
> **Additional context**
> 
> Sileo doesn’t show shshd as an available update even after a few days
> 
>

**Comment by SynnyGR** [comment]
Hi,

This issue has been fixed, a new version should be released soon with the fix.

Best regards
