### ISSUE TITLE
[CRASH]

### ISSUE THREAD

**Issue by iphizzle** [AppTapp/Installer-Issues#183]
**Describe the crash**
A clear description the crash:

i noticed a bunch of crashes in crash reporter. 
![2D63C02E-DF7F-4E91-B039-8E20E376A796](https://user-images.githubusercontent.com/27299905/123178383-b2f5fa80-d44c-11eb-9f65-16d05be9d478.png)

**To Reproduce**

i’m not sure. i just saw them in crash reporter. 
![DCFA1BB4-BA6E-45FC-A5F8-621ACAB2A1A2](https://user-images.githubusercontent.com/27299905/123178443-d325b980-d44c-11eb-9918-65a00ba906ee.png)

**Device (please complete the following information):**
 
- Device: iphone x
 - OS: ios 13.5
 - Installer version: latest stable release
 - Jailbreak: checkra1n 

**Crashlog -- REQUIRED** 
Either upload the crashlog here or upload it to a service like psty.io

https://pastebin.com/iQu7LX31

**Comment by vanwijkdave** [comment]
Did you click on something what caused the crash? that makes it easier for us to reproduce :)

**Comment by iphizzle** [comment]
hello. i can’t remember sensing you a crash report, but i probably did because i usually report crashes. 

the crashes that happen for me in installer always happen when i click on someone’s repo. some times a repo will be set using installer type descriptions and it will crash. then, i’ll go turn on the use original description toggle. & sometime it’s the opposite. sometimes the original depiction causes the crash. but overall the app is very solid. 

i usually just report crashes to devs to help out fixing little problems they might not know about, so it’s not too big of a deal to me. 

thank you for getting back tho

**Comment by vanwijkdave** [comment]
Thanks! Could it be that you were still using installer 5, and not the 5.1 beta?

**Comment by iphizzle** [comment]
i’ve been using the 5.0.3-2 version for a long time. how do i get the beta? it’s been my main package manager for a while.

**Comment by iphizzle** [comment]
i figured it out. thanks for letting me know about it. excited to use it and will definitely report problems

**Comment by vanwijkdave** [comment]
Awesome, thanks!
