### ISSUE TITLE
[BUG] Not all languages are added yet

### ISSUE THREAD

**Issue by socksprox** [AppTapp/Installer-Issues#184]
**Describe the bug**
Language not changing to german after setting it to

I tested it on both iPhone and iPad, and its on both of them

Here a video https://streamable.com/9bjw9r
**To Reproduce**
Do this: https://streamable.com/9bjw9r
Or just change the language to german, and you will see that it does not apply

**Does the issue always occur when trying to reproduce it?** 
Yes

**Expected behavior**
Language is successfully changed to german

**Screenshots or videos**

https://streamable.com/9bjw9r
**Device (please complete the following information):**
 - Installer version: 5.1-85
 - iOS: 14.3, 14.1
 - Jailbreak Unc0ver
 - Device iPhone 12 Mini, iPad 7th gen

**Additional context**

**Comment by vanwijkdave** [comment]
It seems that the german translation isn't fully added to Installer, we'll try to add those ASAP

**Comment by vanwijkdave** [comment]
Added, will be available shortly!
<img width="563" alt="Screenshot 2021-07-08 at 16 25 10" src="https://user-images.githubusercontent.com/31007683/124939007-12393a80-e009-11eb-9b2d-0e36cc380c15.png">
