### ISSUE TITLE
[BUG] Queue button bugging (Video)

### ISSUE THREAD

**Issue by socksprox** [AppTapp/Installer-Issues#185]
**Describe the bug**
https://streamable.com/wgo6tm

**To Reproduce**
Do this: https://streamable.com/wgo6tm

**Does the issue always occur when trying to reproduce it?** 
Yes

**Expected behavior**
Nice animation, without flickering.

**Screenshots or videos**
https://streamable.com/wgo6tm

**Device (please complete the following information):**
 - Installer version: [5.1-85]
 - iOS: 14.3
 - Jailbreak unc0ver
 - Device iPad 2019

**Additional context**

**Comment by vanwijkdave** [comment]
Fixed! Will be available shortly. Thanks for reporting!
