### ISSUE TITLE
[CRASH] Installer 5.1-88 Nightly 

### ISSUE THREAD

**Issue by socksprox** [AppTapp/Installer-Issues#186]
**Describe the crash**
Crashes while trying to install Touchflow from Bigboss
**To Reproduce**
Install touchflow

**Expected behavior**
It installs 

**Screenshots**
Video:  https://streamable.com/jkmjel

**Device (please complete the following information):**
 - Device: iPhone 12 Mini
 - iOS: 14.1
 - Installer version 5.1-88
 - Jailbreak Unc0ver

**Additional context**

**Crashlog -- Cr4shed** 
https://paste.gg/p/anonymous/98f9719205164bec96a44cf53d520903

**Comment by socksprox** [comment]
This happens everytime i try to start tasks

**Comment by socksprox** [comment]
Tested on iPad, same bug

**Comment by vanwijkdave** [comment]
Experimental fix issued, waiting for confirmation...

**Comment by socksprox** [comment]
Confirmed, issue fixed!👍
