### ISSUE TITLE
[Translation][BUG] Installer 5.1-88 does not pick a new line, when the translation is to big in general options

### ISSUE THREAD

**Issue by socksprox** [AppTapp/Installer-Issues#188]
**Describe the issue**
Installer 5.1-88 does not pick a new line when the text gets to big

**To reproduce**
1 Go in settings and set the language to German
2 You will notice that the Buttons of the general options are incorrect because it does not use a new line

https://ibb.co/YTDM6c3 — English Translation (Everything okay, because the text is less)
https://ibb.co/MBK2KFx — German Translation (Buttons are corrupt because the text is to long)

Specs: iPhone 12 Mini iOS 14.1 Installer 5.1-88 Unc0ver

**Comment by vanwijkdave** [comment]
Fixed!
