### ISSUE TITLE
[BUG] Queue does not refresh after deleting the item from it by swiping

### ISSUE THREAD

**Issue by socksprox** [AppTapp/Installer-Issues#189]
**Description**
Queue Button does not refresh after swiping the queue away

**Does this Bug always occur?**
Yes

***Info**
Unfortunately i did not changed the language before uploading the video, so here are the vocabularies you may need
Queue = Warteschlange
Modify = Ändern

**Video**
https://streamable.com/iacrx7

**To reproduce**
1: Add something to the queue
2: Swipe the queue away

Or watch the video: https://streamable.com/iacrx7

**Specs**
Unc0ver 6.2.0 - iPhone 12 Mini - iOS 14.1 - Installer 5.1-87

**How to temporarily fix this**
Tap back, and then go back to the package

**Comment by vanwijkdave** [comment]
ah, it seems that it gets out of the queue button doesn't update right away. Should be an easy enough fix

**Comment by vanwijkdave** [comment]
Fixed!
