### ISSUE TITLE
[BUG] Price of Packages not always loading

### ISSUE THREAD

**Issue by socksprox** [AppTapp/Installer-Issues#191]
**Describe the bug**
Prices are sometimes not loading and it just says Paid

**To Reproduce**
Start installer, and see if there is the Paid button on the tweaks, instead of the price

**Does the issue always occur when trying to reproduce it?** 
No, sometimes the prices are loading

**Screenshots or videos**
https://youtube.com/shorts/TmNP_j7Z7gY?feature=share

**Device (please complete the following information):**
 - Installer version: 5.1-87
 - iOS: 14.1
 - Jailbreak unc0ver
 - Device iPhone 12 Mini

**Comment by vanwijkdave** [comment]
Sadly it is not possible to load the prices at this moment. It's possible on the manually featured packages because i add those to our own database. But it is impossible to do that for all packages 😬

**Comment by socksprox** [comment]
Okay, no problem
