### ISSUE TITLE
[SUGGESTION] Swipe Actions for Reinstalling and choosing version

### ISSUE THREAD

**Issue by socksprox** [AppTapp/Installer-Issues#192]
add to the [Swipe Actions](https://ibb.co/5FxzP9R) an option for downgrading and reinstalling the tweak

**Comment by vanwijkdave** [comment]
Added! :)
![Image from iOS](https://user-images.githubusercontent.com/31007683/126913352-8d220a2e-27af-4cd5-8db1-b117e33865e1.png)
