### ISSUE TITLE
[BUG] Featured Page always  showing get even if the paclsge is installed

### ISSUE THREAD

**Issue by socksprox** [AppTapp/Installer-Issues#196]
**Describe the bug**
Featured Page always  showing „GET“ even if the package is installed. Here a Video where i explain it https://youtube.com/shorts/PXw2mToTTJI?feature=share

**Does the issue always occur when trying to reproduce it?** 
Yes

**Expected behavior**
It should say the right thing

**Screenshots or videos**
https://youtube.com/shorts/PXw2mToTTJI?feature=share

**Device (please complete the following information):**
 - Installer version: 5.1-87
 - iOS: 14.1
 - Jailbreak unc0ver
 - Device iPhone 12 Mini

**Comment by vanwijkdave** [comment]
Fixed!
