### ISSUE TITLE
[BUG] Font Bug

### ISSUE THREAD

**Issue by socksprox** [AppTapp/Installer-Issues#197]
Installer 5.1-87 Font is bugged if you select a tweak from a repo category

https://youtube.com/shorts/tv9QmSRYrfA?feature=share

Specs: iPhone 12 Mini unc0ver 14.3

**Comment by SynnyGR** [comment]
Hi there,

This issue has been fixed lately and shouldn't happen anymore.
Once on a new release, if you still face it I'll let you reopen the issue.

Best regards
