### ISSUE TITLE
[BUG] Can't process apt.procurs.us repo

### ISSUE THREAD

**Issue by theotheroracle** [AppTapp/Installer-Issues#199]
**Describe the bug**
attempting to load repo data from procurs.us fails with "The server responded with invalid data", however it works in sileo and zebra .

**To Reproduce**
Add the https://apt.procurs.us repo

**Does the issue always occur when trying to reproduce it?** 
Yes

**Expected behavior**
The repo data was loaded correctly

**Device (please complete the following information):**
 - Installer version: 5.0.3-2
 - iOS: 12.5.2
 - Jailbreak checkra1n + odysseyra1n
 - Device iPhone 6

**Additional context**

**Comment by turannul** [comment]
Works in Installer 5.1-85

**Comment by AppTapp** [comment]
Installer 5.0.3-2 is an over a year old version, this is fixed on our latest beta! 
https://apptapp.me/betarepo/
