### ISSUE TITLE
[CRASH] Installer crashed after refreshing sources

### ISSUE THREAD

**Issue by socksprox** [AppTapp/Installer-Issues#205]
**Describe the crash**
Can’t say more than the title
**To Reproduce**
For me i just refreshed sources, i don’t think it’s reproduceable that easy. 

**Expected behavior**
Sources should refresh without crash

**Screenshots**
Only crashreport, sry https://paste.gg/p/anonymous/c6264f305c4b4bc7a4b7b7723e4e3d12/files/661e2cac0ac74d1d82f1f3cf5e1bff2e/raw

**Device (please complete the following information):**
 - Device: iPad 2019
 - OS: 14.2
 - Installer version 5.1-88
 - Jailbreak u0 6.2.0

**Crashlog -- REQUIRED** 
https://paste.gg/p/anonymous/c6264f305c4b4bc7a4b7b7723e4e3d12/files/661e2cac0ac74d1d82f1f3cf5e1bff2e/raw

**Comment by SynnyGR** [comment]
Hi there,

Sorry for the late reply.
This issue was due to the memory management system trying to do too much about a package. This has been fixed and should be available within the next release.

Best regards
