### ISSUE TITLE
[CRASH] After clicking on save to library from a photo on a web depiction

### ISSUE THREAD

**Issue by socksprox** [AppTapp/Installer-Issues#206]
**Describe the crash**

https://streamable.com/mri983

**To Reproduce**
1 Go to a package where it shows a web depictions
2 Click on a photo (haptic press) and click save to library
3 Installer 5.1 crashes

**Expected behavior**
Yeah, hmmm what should it do? Not crash?😂

**Screenshots**
No screenshots! Better, i have a video: https://streamable.com/mri983

**Device (please complete the following information):**
 - Device: iPhone 12 Mini
 - OS: iOS 14.1
 - Installer version 5.1-88
 - Jailbreak unc0ver 6.2.0

**Crashlog -- REQUIRED**
https://paste.gg/p/anonymous/a0aa8a0bd9f846aa95f23ca35529387f/files/a71306c13fc94a90ab11ceaf0f3c2fe2/raw

**Comment by SynnyGR** [comment]
Hi again,

The required information has been added to the Installer's plist file, the crash shouldn't happen anymore.

Best regards
