### ISSUE TITLE
IMO we should always be keeping tests in #[cfg(test)] bound submodules to avoid compiling them during non-test use.

### ISSUE THREAD

**Issue by lafi-99** [AppTapp/Installer-Issues#218]
IMO we should always be keeping tests in #[cfg(test)] bound submodules to avoid compiling them during non-test use.

__Originally posted by @james7132 in https://github.com/bevyengine/bevy/pull/3560#discussion_r790052707__

**Comment by vanwijkdave** [comment]
/
