### ISSUE TITLE
Breaks system on dpkg 'Setting up Installer...'

### ISSUE THREAD

**Issue by Dadoum** [AppTapp/Installer-Issues#22]
**Describe the issue**
When I try to install Installer, dpkg crashes on 'Setting up Installer...'. This breaks system and unc0ver until running su; apt remove com.apptapp.installer.

**To Reproduce**
1. Go into Cydia
2. Search for Installer
3. Install it
4. Cydia crashes, device freezes until I force reboot.

**Does the issue always occur when trying to reproduce it?**
Yes

**Expected behavior**
Install Installer

**Screenshots**

**Device (please complete the following information):**
 - Device: iPhone9,1 (7 Global)
 - OS: 12.4
 - Version Latest on post date
 - Jailbreak unc0ver

**Additional context**
*I was able to install Installer before.* But one day, Installer failed when I searched repo, and it could not restart, so after trying uicache, reboot and other things like that, I tried to reinstall Installer but this issue came up.

Edit: `dpkg --configure -a` after the reboot make system freezing too.

**Comment by CreatureSurvive** [comment]
This sounds like a potential issue the initial time you uninstalled Installer, but it’s difficult to determine exactly. Would you mind posting your status file located in`/Library/dpkg/status` so I can look into this further?

**Comment by Dadoum** [comment]
https://drive.google.com/file/d/18vDQ-5KZu-vTXw1zFaVDSP2XN-PD6Phb/view?usp=drivesdk Here it is !

**Comment by Dadoum** [comment]
@CreatureSurvive any news ?

**Comment by Dadoum** [comment]
I added it like 2 weeks ago, any news ?

**Comment by Dadoum** [comment]
Install it through checkra1n fixed the issue (how ?)

**Comment by Dadoum** [comment]
Rehappened after an upgrade to 13.3

**Comment by Dadoum** [comment]
OK, found the issue in postinst script: 
```
chown -R mobile:mobile "/var/mobile/Library/Application Support/Installer"
```
System crashes on executing this command, so I runned:
```
rm -rf "/var/mobile/Library/Application Support/Installer"
mkdir "/var/mobile/Library/Application Support/Installer"
```
And it recreated my Installer config folder and it worked again.
