### ISSUE TITLE
Downloading from paid repo

### ISSUE THREAD

**Issue by bill88t** [AppTapp/Installer-Issues#23]
When attempting to download/update/remove a paid package from a repository, if you're not signed in, you are forced to. Some stores though for instance Sparkdev's do not register from Installer. So even though I'm vip I can't even remove installed packages from his repo.

Installer version: 5.0.1

**Comment by CreatureSurvive** [comment]
We’ve resolved this issues with SparkDev repo and it will no longer require logging for queuing packages. We will also change the behavior so that sign-in is not required for package removal. Thanks for reporting, these fixes will be available in v5.0.2 soon.
