### ISSUE TITLE
[BUG] queue confirm button stuck in “waiting” state

### ISSUE THREAD

**Issue by xxthepersonx** [AppTapp/Installer-Issues#24]
**Describe the bug**
The install button stays on "Waiting..." even after you can clearly press the button. Maybe this button should say "Confirm" or "Proceed"?

**To Reproduce**
Steps to reproduce the behaviour:

Go to any package, add to queue, go to queue, and look at install button. 

**Does the issue always occur when trying to reproduce it?** 
Yes

**Expected behavior**
"Waiting..." button should turn to maybe "Confirm" or "Proceed" 

**Screenshots or videos**

https://imgur.com/gallery/eDEQWNi

**Device (please complete the following information):**
 - Installer version: [5.0.1]
 - iOS: [11.4]
 - Jailbreak [unc0ver]
 - Device [iPhone 7 Plus]

**Additional context**
seems to happen with all packages added into queue. Also seems to happen whether one package is added or more than one. Other than that, loving installer 5 so far 😀

**Comment by CreatureSurvive** [comment]
Thank you for letting us know, we will investigate this issue today, and it should be resolved in the next release.
