### ISSUE TITLE
[CRASH] when toggling “show original depictions” on add source view

### ISSUE THREAD

**Issue by seitanmen** [AppTapp/Installer-Issues#25]
Show original depiction toggle bug.

Device:iPhone X (Cellular)
iOS:13.2.3
Installer version:5.0.1

Tapping in this state will crash
![7DF556FB-0447-458F-8287-975539294E50](https://user-images.githubusercontent.com/35191853/72519836-82934f80-389b-11ea-8524-fdc903fe8ca7.jpeg)

**Comment by CreatureSurvive** [comment]
Thanks for letting us know, we will get this taken care of before the next release.
