### ISSUE TITLE
[CRASH]

### ISSUE THREAD

**Issue by ghost** [AppTapp/Installer-Issues#27]
Describe the crash:
A button you press that crashes the app

To Reproduce: 
1. Open the “Manage” tab at the bottom
2. Press the “+”
3. 
![60FF991D-E123-42E4-A766-E3855336B0EC](https://user-images.githubusercontent.com/43425311/72752791-f8d3d280-3b77-11ea-82d0-be0fba511de6.jpeg)

Press that button and boom, crash...

Expected behavior:
I didn’t know what to expect, I’m new to the app and decided to press it to see what happens.

 - Device: iPhone X
 - OS: iOS 12.4
 - Installer version: 5.0.1
 - Jailbreak: Unc0ver 3.8.0-b1

**Crashlog -- REQUIRED** 
Have no idea where the crash log is located, could’ve at least said the file location so I can find it with Filza...

**Comment by CreatureSurvive** [comment]
This has been fixed in the current beta build, we will be releasing it soon to address a number of issues.
