### ISSUE TITLE
[BUG] Substrate Dependency

### ISSUE THREAD

**Issue by Turkay7879** [AppTapp/Installer-Issues#29]
If the device is jailbroken for the first time and Cydia Substrate is not installed, while queueing the tweaks in Installer, Installer doesn’t let you to install any tweak that depends on Substrate rather than adding Cydia Substrate to the queue too.

This problem can be reproduced by jailbreaking the device with Checkra1n for the first time, adding the AppTapp repo to Cydia and install the Installer right away.

Instead of giving a message that says Installer can’t install X tweak, Installer should add Cydia Substrate to the queue to install that too.

**Device (please complete the following information):**
 - Installer version: 5.0.1
 - iOS: 12.4.4
 - Jailbreak: Checkra1n
 - Device: iPhone 5s

**Comment by SammyGuichelaar** [comment]
This issue may be related to the default repositories we use for Checkra1n, which may need to be updated, thank you for the report.

**Comment by AppTapp** [comment]
Fixed with bootstrap repository updates in recent versions.
