### ISSUE TITLE
[BUG] The app doesn’t retain login session when closed

### ISSUE THREAD

**Issue by avltree9798** [AppTapp/Installer-Issues#31]
Describe the bug
The app doesn’t retain the login session when closed(ie removed from the list in multitasking menu). Every-time the app is freshly launched, it shows login screen as if it was opened the first time

To Reproduce
Open the app, login, and force close the app. Then relaunch again

Does the issue always occur when trying to reproduce it?
Yes

Expected behavior
The login session should be retained even when the app is closed.

Device (please complete the following information):

Installer version: 5.0.2.2
iOS: 13.3
Jailbreak checkra1n 0.9.8
Device iPhone X

**Comment by avltree9798** [comment]
This issue is related to https://github.com/AppTapp/Installer-Issues/issues/20
But I already use the latest version of the Installer and the issue still present

**Comment by avltree9798** [comment]
And also after importing Cydia repo, and closing the app, after re-opening it again, the repo is gone

**Comment by SammyGuichelaar** [comment]
@avltree9798 Thank you for your report! We are unable to reproduce the issue ourselves, can you confirm if you still have this issue?

**Comment by avltree9798** [comment]
> @avltree9798 Thank you for your report! We are unable to reproduce the issue ourselves, can you confirm if you still have this issue?

Yep, the issue is still there.

**Comment by MiladShojaei** [comment]
We (me and my friends) also have this problem too with last version

**Comment by AppTapp** [comment]
No matter what we do we cannot reproduce this issue. We are still looking into this.
