### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by fattyz** [AppTapp/Installer-Issues#32]
**Describe the bug**. Not bug
“Unable to fix problems you have held broken packages”. 

Device 
6s plus
 - Installer version: [e.g. 5.0RC3-1]
 - iOS: 13.3.1
 - Jailbreak  Checkra1n bootra1n linuxusb 
 
Thank you

**Comment by SammyGuichelaar** [comment]
Please update to the latest version of Installer. You are using a very outdated version.
