### ISSUE TITLE
[BUG] Manually updating an ignored update to a specific version does not work

### ISSUE THREAD

**Issue by Dominik-zitrone** [AppTapp/Installer-Issues#34]
**Describe the bug**

When you select "ignore updates" for a tweak, but there is an update and you click on "select version" and select a newer version than installed (so you try to update manually), then it won't do the planned update procedure (because of "ignore updates" enabled).

**To Reproduce**
Steps to reproduce the behaviour:
Example Tweak: latest version 1.1, your version 1.0,

1. be on 1.0 
2. click "ignore update" for this tweak
3. click "select version" for this tweak
4. click the latest (in this case 1.1)
5. do the update 
6. it won't do the manually forced update to this version
**Does the issue always occur when trying to reproduce it?** 
Yes/No
Yes
**Expected behavior**
You can not force it to update to the newer version
**Screenshots or videos**
If applicable, add screenshots or videos to help explain your problem.
-
**Device (please complete the following information):**
 - Installer version: [e.g. 5.0RC3-1]
 - iOS: [e.g. iOS 12.1.2]
 - Jailbreak [e.g. Checkra1n]
 - Device [e.g. iPhone X]
-iOS 13.3.1 
-Checkra1n 
-iPhone X
**Additional context**

**Comment by Saud99** [comment]
Not sure

**Comment by AppTapp** [comment]
That's a good catch, we'll add it on our to-do list!
