### ISSUE TITLE
[SUGGESTION] Multitasking Support for iPadOS

### ISSUE THREAD

**Issue by ghost** [AppTapp/Installer-Issues#36]
i don‘t want to waste your time.
It would be amazing if you added multitasking support for ipados! it _seems_ simple to do but I honestly have no idea if it really is.

**Comment by AppTapp** [comment]
Could you clarify what you mean by Multitasking on iPadOS, and how it differs from what Installer currently does?

**Comment by ghost** [comment]
Installer 5 is a great package manager, but unfortunately it does not support multitasking on iPadOS, such as split view (https://youtu.be/nSBZKr5kXYM) and slide over (https://youtu.be/ITzy5J3j5Is). It seems easy to add that feature, but I‘m not a programmer, so sorry if I‘m wrong.

The feature would be cool to be added, because sometimes downloading tweaks can take a long time and if you can just have installer 5 in slide over, you can do something else while you wait.
I hope you could understand me.
