### ISSUE TITLE
[SUGGESTION] Fix broken Spanish Translations

### ISSUE THREAD

**Issue by Xpl0itU** [AppTapp/Installer-Issues#38]
Yesterday I fixed most of the broken Spanish translations in crowdin, most of them made no sense or were really important mistakes, If the team wants, I can translate the whole project as there are a lot of untranslated strings or badly translated ones.

**Comment by AppTapp** [comment]
We are completely redesigning Installer, which means most of the app will need to be retranslated once the beta becomes available. When this is the case, we would very much appreciate your Spanish translations :-)

**Comment by Xpl0itU** [comment]
Sure, just tell me when they are avaliable to transalte
