### ISSUE TITLE
[BUG] No tweak compatibility indicator

### ISSUE THREAD

**Issue by KibSquib48** [AppTapp/Installer-Issues#39]
**Describe the bug**
There is no tweak compatibility indicator on any package

**To Reproduce**
Steps to reproduce the behaviour: look up a tweak, there’s no compatibility indicator

**Does the issue always occur when trying to reproduce it?** 
Yes

**Expected behavior**
An indicator shows if the tweak is compatible

**Device (please complete the following information):**
 - Installer version: 5.0.2.3
 - iOS: 13.3
 - Jailbreak: checkra1n
 - Device: iPhone 8

**Comment by AppTapp** [comment]
This is by design, but will be addressed in the upcoming 5.1 redesign.
