### ISSUE TITLE
[SUGGESTION] Source exporting/syncing

### ISSUE THREAD

**Issue by M1staAwesome** [AppTapp/Installer-Issues#4]
**Is your feature request related to a problem? Please describe.**
It’d be helpful whenever I occasionally use Cydia for something to have all of my sources be able to be moved over.

**Describe the solution you'd like**
It would be ideal to be able to have repos sync between Installer and Cydia (and other package managers too), but if that’s impossible/too complicated, a source export button would be fine.

**Comment by CreatureSurvive** [comment]
We’ve added source export options a few releases ago. And as of now we do not plan on syncing sources with other package managers as not everyone would want that behavior. This would also be a feature that could break at any time due to updates of other PMs. I’ll go ahead and close this.
