### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by ommieokay** [AppTapp/Installer-Issues#40]
**Describe the bug**
A clear and concise description of what the bug is. whenever i try to download or remove something it tells me to unmet dependencies. 

**To Reproduce**
Steps to reproduce the behaviour:

**Does the issue always occur when trying to reproduce it?** 
Yes/No yes

**Expected behavior**

**Screenshots or videos**
If applicable, add screenshots or videos to help explain your problem.

**Device (please complete the following information):**
 - Installer version: [e.g. 5.0RC3-1]
 - iOS: [e.g. iOS 12.1.2]
 - Jailbreak [e.g. Checkra1n]
 - Device [e.g. iPhone X]

**Additional context**

**Comment by AppTapp** [comment]
No context. If you have an issue please open a new issue with context.
