### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by JaCrissspy** [AppTapp/Installer-Issues#41]
Sorry this isn’t a bug this is a suggestion for apptapp you should have like the tweak of the day where it’s the most downloaded for the day or just a popular tweak for the day. Thanks.

**Comment by AppTapp** [comment]
We have Most downloaded which gets reset every week. This was an API change made after this issue was opened so I am satisfied this issue is resolved. If you think otherwise, please reach out to us or reopen an issue :-)
