### ISSUE TITLE
[BUG] undersired-design Installer 5 dominates Cydia web links

### ISSUE THREAD

**Issue by cottontails2** [AppTapp/Installer-Issues#42]
**Describe the issue**
I am trying to install Velox Reloaded from the Chariz repo, but I can’t install it directly from Installer 5, because of the way you have to pay for the app. So when purchasing on Cydia it takes me to login to the Chariz repo and upon purchasing the tweak I get a link saying open in Cydia, but when I click on it a message pops up saying open in Installer 5. I can’t seem to open it in Cydia it automatically defaults to Installer 5 everytime, so I can’t verify the purchase on Cydia since the link won’t open in Cydia and I can’t install it in Installer 5 either since it’s a paid app. I tried signing into Cydia through the Installer 5 app by going to Stores section but the app is not listed since it can't be verified through Cydia and I have found no option to sign into the Chariz repo through Installer 5.

**To Reproduce**
Clicking on the link always results in Installer 5 message to install instead of opening in Cydia, if it wasn’t clear this is a link specific to Cydia, but for some reason Installer 5 takes over the link. Here is the exact link: https://chariz.com/buy/velox-reloaded/launch-cydia

**Does the issue always occur when trying to reproduce it?**
Yes

**Expected Behavior**
There should be an option/toggle in settings to prevent Installer from taking over Cydia links or communicate with the Chariz repo to add support for purchasing their paid apps and logging in through Installer 5.

**Screenshots**
<details>
  <summary>Reveal Screenshots</summary>

![90961493_2841517815938299_6939214304633683968_n](https://user-images.githubusercontent.com/26862671/77639425-fe51ee00-6f15-11ea-92ef-1d5af4fce188.jpg)
![90470011_508707460069374_1408847683673653248_n](https://user-images.githubusercontent.com/26862671/77639449-04e06580-6f16-11ea-9094-1e0ea10f11ea.jpg)
![90941566_698761550928077_7478103370226466816_n](https://user-images.githubusercontent.com/26862671/77639460-06aa2900-6f16-11ea-8437-ba368fcefc51.jpg)
![91445921_880707262371609_3215561234770296832_n](https://user-images.githubusercontent.com/26862671/77639843-9c45b880-6f16-11ea-976f-6fd36a0db384.jpg)
 
</details>

**Device (please complete the following information):**
 - Device: iPhone X
 - OS: IOS 13.3
 - Version: Installer 5.0.2.4

 - Jailbreak [e.g. Checkra1n]
Unc0ver 4.3.1

**Additional context**
I don’t think there is anything else to add, but thank you for taking the time to read this and I hope you can assist me with this problem.

-Alice

**Comment by AppTapp** [comment]
Fixed in 5.0.3.

Installer should be able to support the full purchase chain on any Cydia repo using the Sileo payment API, if you are still facing this issue could you open an issue for that?
