### ISSUE TITLE
[BUG] Chariz repo store login

### ISSUE THREAD

**Issue by thetechwizard17** [AppTapp/Installer-Issues#43]
**Describe the bug**
When updating to new version of installer in the store login section Chariz repo disappears

**To Reproduce**
Steps to reproduce the behaviour:
Update to newest version 

**Does the issue always occur when trying to reproduce it?** 
Yes

**Expected behavior**

**Screenshots or videos**
If applicable, add screenshots or videos to help explain your problem.

**Device (please complete the following information):**
 - Installer version: 5.0.2.4
 - iOS: 13.3
 - Jailbreak unc0ver
 - Device iPhone 11 Pro Max

**Additional context**

**Comment by thetechwizard17** [comment]
[Video.zip](https://github.com/AppTapp/Installer-Issues/files/4387983/Video.zip)

**Comment by AppTapp** [comment]
Should be fixed in later versions. If the issue is still persistent please open new issue.
