### ISSUE TITLE
[CRASH] Application crashes when i open any source

### ISSUE THREAD

**Issue by abdullah5490** [AppTapp/Installer-Issues#44]
**Describe the crash**
When I open any repo from my sources to view it's packages, the application crashes immediately. I'm a voiceover user, so it might happened due to the accessibility service, but it should be fixed.

**To Reproduce**
1. turn on voiceover on your phone.
2. open installer and go to "manage" tab.
3. Click on any repo in the sources list to open it's packages list.
4. try to read the screen by focussing finger to any item, or by swiping to navigate to the next item. The application will instantly crash when you try to do so.

**Device (please complete the following information):**
 - Device: iPhone7 global
 - OS: iOS13.3
 - Installer version latest, 5.0.24.
 - Jailbreak: Checkra1n

**Additional context**
I'm not sure that it is happening for regular users or not, but this is the problem if we are using the iOS build-in accessibility service. Please fix it, so we can enjoy this package manager easily without any hurdel.

**Comment by calors** [comment]
me too.  
https://apt.margua.top/
https://apt.coolstar.xyz/
https://apt.xbsite.cn/
the three source crash for me 

btw,iPhone x 13.4

**Comment by AppTapp** [comment]
We were unable to reproduce this issue, could you confirm if this issue is still persistent on the latest version of Installer?

**Comment by abdullah5490** [comment]
yes it is.
