### ISSUE TITLE
http://apt.thebigboss.org/repofiles/cydia/

### ISSUE THREAD

**Issue by rwad784** [AppTapp/Installer-Issues#47]
**Describe the issue**

**To Reproduce**
1.
2.
3.
4.

**Does the issue always occur when trying to reproduce it?**
Yes/No

**Expected behavior**

**Screenshots**

**Device (please complete the following information):**
 - OS: [e.g. iOS 12.4]
 - Version [e.g. Installer 5 beta 9]
 - Jailbreak [e.g. Checkra1n]

**Additional context**

**DO NOT FORGET TO LABEL THIS REPORT**

**Comment by AppTapp** [comment]
No context. If you have an issue please open a new issue with context.
