### ISSUE TITLE
[BUG] Unable to Install 'TetherMe' from official repo.

### ISSUE THREAD

**Issue by dallasco** [AppTapp/Installer-Issues#5]
**Describe the bug**
When attempting to download TetherMe from the official repo, an error occurs stating that the version could not be found and installer leaves a half-installed package of TetherMe behind. In Cydia, it will also show TetherMe as installed, when the tweak in fact never installed.

**To Reproduce**
Add repo - https://repo.tetherme.com/licensed/ and attempt to download the package.
(note: payment is not required to download the package)

**Does the issue always occur when trying to reproduce it?** 
Yes

**Device (please complete the following information):**
 - Installer version: [e.g. 5.0RC6-1]
 - iOS: 13.3
 - Jailbreak: Checkra1n
 - Device: iPhone X

edit: Fixed repo URL

**Comment by CreatureSurvive** [comment]
I’m not sure if you have the wrong URL, or if the repo is down/moved. Currently there is no repo hosted at the link provided here.

**Comment by dallasco** [comment]
![2740C7A8-1DB0-4696-9466-7DDE4F01BD51](https://user-images.githubusercontent.com/25357605/70950515-d7d70980-202e-11ea-9dc5-480bbaa83ce2.jpeg)

Sorry you’re right, I mistyped it.

**Comment by CreatureSurvive** [comment]
This issue has finally been fixed in the upcoming release, TetherMe should now show in the repo, and download correctly. This should fix similar issues with other repos as well.
