### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by ThuanOfficial** [AppTapp/Installer-Issues#52]
**Describe the bug**  is: Can you make the history tab when u search have clear button so we can clear thing we search.
**Device (please complete the following information):**
 - Installer version: [e.g. 5.0RC3-1]
 - iOS: [e.g. iOS 12.1.2]
 - Jailbreak [e.g. Checkra1n]
 - Device [e.g. iPhone X]

**Comment by AppTapp** [comment]
This will be added in the 5.1 update. Closing for now.
