### ISSUE TITLE
installer not being default instead it’s Cydia 

### ISSUE THREAD

**Issue by Skeam56** [AppTapp/Installer-Issues#53]
**Describe the issue**

Installer not opening repo links directly to installer instead of Cydia. Previous version before new update did. 

**To Reproduce**
None

**Does the issue always occur when trying to reproduce it?**
Need to go back to previous version for installer to be my default installer rather than cydia 

**Expected behavior**
Like previous version. I was able to press on a link on a repos website to add the repo and it would open as default to installer new update does it but for cydia

**screenshot**
![88FC69FE-C626-4D9F-901D-D5BCD7DF7B6A](https://user-images.githubusercontent.com/57741144/79373464-d6055000-7f13-11ea-8ac8-babf1b4ce7b7.png)

**Device (please complete the following information):**
 - Device: [iphone x ]
 - OS: [e.g. iOS 13.3]
 - Version [e.g. Installer 5 newest version]
 - Jailbreak [e.g. uncover newest version]

**Additional context**

**DO NOT FORGET TO LABEL THIS REPORT**

**Comment by AppTapp** [comment]
This is a new feature, you can change this behaviour in Settings.
