### ISSUE TITLE
[BUG] DPKG was interrupted

### ISSUE THREAD

**Issue by CantelopePug** [AppTapp/Installer-Issues#55]
**Describe the issue***
i’ve been trying to install tweaks for a while and i’ve gotten errors a couple days ago all of a sudden. I’ve installed tweaks before.the error says something bout dpkg was interrupted.

**To Reproduce**
1. Respring Phone
2. Try and install a tweak
3. then error pops up

**Does the issue always occur when trying to reproduce it?**
Yes

**Expected behavior**
It’s supposed to install tweak

**Screenshots**
![A088A120-C044-41D5-8D67-24DD1C0F909A](https://user-images.githubusercontent.com/59425979/80266627-8127af00-8662-11ea-9fcf-2ccd04979d6d.png)

**Device (please complete the following information):**
 - Device: iPhone 7 Plus
 - OS: iOS 13.3.1
 - Version : 5.0.3-2
 - Jailbreak :Checkra1n

**Additional context**
it happens when i try to install and update tweaks( removing works fine)

**Comment by AppTapp** [comment]
Do you still experience this issue? We were unable to reproduce it on our side unfortunately.
