### ISSUE TITLE
[SUGGESTION] Filter out specific developers in Installer

### ISSUE THREAD

**Issue by kegobass** [AppTapp/Installer-Issues#56]
**Is your feature request related to a problem? Please describe.**
It would be a nice feature to be able to filter out specific developers when updating repos

**Describe the solution you'd like**
A setting to filter out devs so when the repos update, it skips or hides these items in the list

**Screenshots if available**
N/A

**Describe alternatives you've considered**
Zebra beta has this feature

**Additional context**
N/A

**Comment by AppTapp** [comment]
The feature is in development, and will be introduced soon. Will close issue once feature is public.
