### ISSUE TITLE
[CRASH] When searching for same package multiple times

### ISSUE THREAD

**Issue by davex2012** [AppTapp/Installer-Issues#57]
**Describe the crash**
When searching same app name multiple times. Can’t select specific app if I search same apps name multiple times I can’t select the apps instead open all the apps list.

**Device (please complete the following information):**
 - Device: [iPhone Xs]
 - OS: [. iOS 13.3]
 - Installer version [5.3]
 - Jailbreak [unc0ver 

**Crashlog -- REQUIRED** 
[Log](https://psty.io/f?q=555)

**Comment by AppTapp** [comment]
Looking into the issue, will report back with updates.
