### ISSUE TITLE
[BUG]can not search with Chinese characters 

### ISSUE THREAD

**Issue by androidcn** [AppTapp/Installer-Issues#58]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:

**Does the issue always occur when trying to reproduce it?** 
Yes/No

**Expected behavior**

**Screenshots or videos**
If applicable, add screenshots or videos to help explain your problem.

**Device (please complete the following information):**
 - Installer version: [e.g. 5.0RC3-1]
 - iOS: [e.g. iOS 12.1.2]
 - Jailbreak [e.g. Checkra1n]
 - Device [e.g. iPhone X]

**Additional context**

**Comment by AppTapp** [comment]
We were unable to reproduce this issue, in multiple examples it worked on our end. Could you try again, reopen if the issue still persists and give an example?
