### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Skeam56** [AppTapp/Installer-Issues#59]
**Describe the bug**
Previous version before newest version when adding a repo from safari I would get an alert that it would be open with installer now it says “open with Cydia”.

**To Reproduce**
Nonw

**Does the issue always occur when trying to reproduce it?** 
Yes

**Expected behavior**
Being able to add repos from safari and opening default to installer rather than cydia  like previous version. 

**Screenshots or videos**
If applicable, add screenshots or videos to help explain your problem.

**Device (please complete the following information):**
 - Installer version: 5.0.3
 - iOS: 13.3
 - Jailbreak: unc0ver
 - Device iPhone x

**Additional context**
None 
![E0BADF02-27C8-4257-92CD-77D71B7ED537](https://user-images.githubusercontent.com/57741144/81248333-b5478c00-8fe1-11ea-8db6-2b6ec8e25d91.png)

**Comment by SammyGuichelaar** [comment]
Not an issue. This is expected behaviour. You can 'hook' Cydia's URL scheme in Installer settings.
