### ISSUE TITLE
[BUG]App crashes when quickly tap on manage tab after opening the app

### ISSUE THREAD

**Issue by Netsurfer35** [AppTapp/Installer-Issues#6]
**Describe the bug**
when I newly open the app and quickly tap on the manage tab it sometimes closes.
**To Reproduce**
Steps to reproduce the behaviour:

-open Installer app
-tap on manage

**Does the issue always occur when trying to reproduce it?** 
No

**Device (please complete the following information):**
 - Installer version: 5.0RC6-1
 - iOS: iOS 13.3
 - Jailbreak: Checkra1n
 - Device: iPhone X

**Comment by CreatureSurvive** [comment]
Can you provide a crashlog for this, I am unable to reproduce this issue on our end. If you don’t have any crashlogs for this, then can you provide the log file located at `/var/mobile/Library/Log/me.apptapp.installer/installer.log` this would be a huge help in tracking down the cause of the crash.

**Comment by AppTapp** [comment]
Issue solved by RC9

**Comment by Netsurfer35** [comment]
Dear Installer team,


I recently reported a bug on github where the app crashes on launch and I received an email saying it will be fixed with rc9 but it didn’t so I sending new crashlogs with this email to help you fix this issue.


Greetings Calvin.
