### ISSUE TITLE
[CRASH] Updating packages after install

### ISSUE THREAD

**Issue by icharlse** [AppTapp/Installer-Issues#60]
Could not open lock file /var/lib/Debian Packager/lock-frontend - open (2: No such file or directory)
E: Unable to acquire the Debian Packager frontend lock (/var/lib/Debian Packager/lock-frontend), are you root?

**Comment by AppTapp** [comment]
Did Installer crash during install or did you close the installation screen?

**Comment by icharlse** [comment]
It crashes...

Charles Isabirye  --- Click to view my portfolio
<https://www.linkedin.com/in/icharlse/>

*Rwanda: *+250 787 113 065 | *Kenya:* +254 724 589 814 | *Tanzania:* +255
764 003 184



Disclaimer - The information transmitted is intended only for the person or
entity to which it is addressed and may contain confidential and/or
privileged material. If you received this in error, please contact the
sender and delete the material from the device.

**Comment by AppTapp** [comment]
@icharlse I deleted the comment since it contained personal phone numbers & other information. We’ll look at the issue.
