### ISSUE TITLE
[BUG] welcome screen every time I close the app

### ISSUE THREAD

**Issue by MiladShojaei** [AppTapp/Installer-Issues#61]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:

**Does the issue always occur when trying to reproduce it?** 
Yes/No

**Expected behavior**

**Screenshots or videos**
If applicable, add screenshots or videos to help explain your problem.

**Device (please complete the following information):**
 - Installer version: [e.g. 5.0RC3-1]
 - iOS: [e.g. iOS 12.1.2]
 - Jailbreak [e.g. Checkra1n]
 - Device [e.g. iPhone X]

**Additional context**

**Comment by MiladShojaei** [comment]
iphone 7
Checkra1n 
13.3

**Comment by AppTapp** [comment]
What Installer version are you using?

**Comment by MiladShojaei** [comment]
Last version
