### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Vastomo** [AppTapp/Installer-Issues#71]
[image](https://i.imgur.com/wTKsTav.jpg) **Describe the bug**

Shows real sources have failed when Cydia says they work

**To Reproduce**
Steps to reproduce the behaviour:

**Does the issue always occur when trying to reproduce it?** 
Yes/No

**Expected behavior**
Repos are up and working

**Screenshots or videos**
If applicable, add screenshots or videos to help explain your problem.

**Device (please complete the following information):**
 - Installer version: [e.g. 5.0RC3-1]
Latest as of 25/05/2020

 - iOS: [e.g. iOS 12.1.2]
13.5

 - Jailbreak [e.g. Checkra1n]
Unc0ver

 - Device [e.g. iPhone X]
iP7+
**Additional context**

**Comment by AppTapp** [comment]
Is this issue still present as of today? The jailbreak release took down multiple repositories at the same time, and we have not seen any other reports regarding this.

**Comment by Vastomo** [comment]
Yes I still am having this issue. Would there be anything I can do to help?
