### ISSUE TITLE
[SUGGESTION] Design issue with toggles under Interface Style

### ISSUE THREAD

**Issue by PoomSmart** [AppTapp/Installer-Issues#72]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Blue/Grey/OLED darkmode are different options. Only one of them can be enabled - rather, selected at a time. This group of options should have been checkmarks.

**Screenshots if available**
![IMG_0246](https://user-images.githubusercontent.com/3608783/82906995-3fa36000-9f90-11ea-8848-ac55aa91480c.jpeg)

**Describe alternatives you've considered**

**Additional context**

**Comment by AppTapp** [comment]
Thank you for your report. This is planned for Installer 5.1 along with other design changes. I will leave this issue open until it has been fixed in the. 5.1 release.
