### ISSUE TITLE
[BUG] no dark mode

### ISSUE THREAD

**Issue by explorerjb** [AppTapp/Installer-Issues#78]
**Describe the bug**
no dark mode at all on installer

**To Reproduce**
Steps to reproduce the behaviour:
open installer 

**Does the issue always occur when trying to reproduce it?** 
Yes

**Expected behavior**
i expected to see installer with dark mode but instead my eyes were blinded by white

**Screenshots or videos**
If applicable, add screenshots or videos to help explain your problem.

**Device (please complete the following information):**
 - Installer version: [e.g. 5.0RC3-1]
 - iOS: [e.g. iOS 12.1.2]
 - Jailbreak [Unc0ver]
 - Device [iPhone 11]

**Additional context**

**Comment by AppTapp** [comment]
Installer contains 3 different dark modes, go to Installer settings to enable or change them.
