### ISSUE TITLE
[BUG] weird glitch at startup with RC6

### ISSUE THREAD

**Issue by aRvedk** [AppTapp/Installer-Issues#9]
**Describe the bug**
Since RC6 there’s a weird/transparent glitch when starting the app. 

**To Reproduce**
Steps to reproduce the behaviour:
Close installer from app switcher and open installer. 

**Does the issue always occur when trying to reproduce it?** 
Yes as soon as you close installer. Tried already with tweaks disabled and safe mode. 

**Expected behavior**
No transparent blurry GUI at start up :-) 

**Screenshots or videos**
https://cdn.discordapp.com/attachments/634767925282078751/656146904865832960/video0.mp4

**Device (please complete the following information):**
 - Installer version: 5.0RC6-1
 - iOS: 13.3
 - Jailbreak Checkra1n
 - Device iPhone 7

**Additional context**
2 other people on discord got the same glitch.

**Comment by CreatureSurvive** [comment]
After investigation, this is an issue with iOS and the way launch screen snapshots are cached. There is nothing we can do internally to resolve this, all you can do is wait for iOS to purge the snapshot cache for installer and launch images/resume snapshots will work again.
