### ISSUE TITLE
[CRASH]

### ISSUE THREAD

**Issue by srikar161720** [AppTapp/Installer-Issues#93]
Sometimes when I click on a tweak the app just crashes and have no clue as to why.

I’m not sure how you would reproduce this. It happens at random.

When it occurs, the app just completely crashes and Cr4shed picks it up.

No screenshots available, sorry.

**Device (please complete the following information):**
 - iPhone 10,6
 - iOS 13.4.1
 - Installer version 5.0.3
 - Unc0ver 5.2.1

According to Cr4shed, this is the reason:
“Modifications to the layout engine must not be performed from a background thread after it has been accessed from the main thread.”

Crash log: https://psty.io/p?q=bedd3

**Comment by AppTapp** [comment]
Fixed in the upcoming release of 5.1
